### ISSUE TITLE
add libzbvi to the default options in Homebrew formula from your repo

### ISSUE THREAD

**Issue by Vincent-Dabouineau** [homebrew-ffmpeg/homebrew-ffmpeg#105]

**Comment by retokromer** [comment]
Hello @Vincent-Dabouineau : could you possibly test if [this branch](https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/tree/libzvbi) works on your end?

**Comment by Vincent-Dabouineau** [comment]
> Hello @Vincent-Dabouineau : could you possibly test it?

I'm sorry but whatever I'm installing ZVBI from `Homebrew` or manually, same issue:
`ERROR: zvbi-0.2 not found using pkg-config

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.libera.chat.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/issues

These open issues may also help:
Brewing custom ffmpeg but failure at metal execution https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/issues/96`

**Comment by Vincent-Dabouineau** [comment]
> Hello @Vincent-Dabouineau : could you possibly test it?

Always the same build issues mentioned in my previous post, else building first libzvbi from source or using Homebrew. Maybe the ffmpeg.rb should be enhanced with the same jack spirit (not expert with ruby):

`if build.with? “jack”
      ENV.prepend_path “PKG_CONFIG_PATH”, Formula[“jack”].opt_lib/“pkgconfig”
      args << “—enable-libjack”
      args << “—enable-indev=jack”
    end
`
How do you make the build working in macOS Monterey?

**Comment by retokromer** [comment]
Except the mentioned, patched, five-year-old [solution](https://github.com/johnwheeler/homebrew-ffmpeg-with-zvbi) that works for FFmpeg 3.3.2, I do not know a Homebrew formula for `libzvbi`. Which formula did you use, @Vincent-Dabouineau?

Our FFmpeg formula considers the last release, which is 5.0.1. FFmpeg 3.2 is very old: it’s the default for Debian 9 that however will be supported only until 2022-06-30.

Note that we are not `libzvbi` maintainers.

**Comment by Vincent-Dabouineau** [comment]
I used in the past the same building workflow with a 4.x FFmpeg Hombrew formula and it was working.

**Comment by retokromer** [comment]
Oops! I notice that I messed up FFmpeg 3.2 and 3.3. I guess, the 3.3 branch is no longer maintained.

I was asking what Homebrew formula you did use to install `libzvbi`? I don’t know of any myself. Otherwise I cannot reproduce…

**Comment by Vincent-Dabouineau** [comment]
> Except the mentioned, patched, five-year-old [solution](https://github.com/johnwheeler/homebrew-ffmpeg-with-zvbi) that works for FFmpeg 3.3.2, I do not know a Homebrew formula for `libzvbi`. Which formula did you use, @Vincent-Dabouineau?
> `from my self fork : https://github.com/LesCanauxDiscrets/homebrew-tap/blob/master/Formula/zvbi.rb`
> Our FFmpeg formula considers the last release, which is 5.0.1. FFmpeg 3.2 is very old: it’s the default for Debian 9 that however will be supported only until 2022-06-30.
> 
> Note that we are not `libzvbi` maintainers.

**Comment by retokromer** [comment]
As said, this is old: `zvbi` 0.2.35 has been released on 2013-08-28, that’s almost nine years ago. You have to modify your formula (or patch the code) to make it working on today’s machines, such as AArch64 (M1) running macOS 12.4.
