### ISSUE TITLE
Please enable the ffplay building option, as the official brew formula does

### ISSUE THREAD

**Issue by Vincent-Dabouineau** [homebrew-ffmpeg/homebrew-ffmpeg#107]
`brew install homebrew-ffmpeg/ffmpeg/ffmpeg --with-fdk-aac --with-jack --with-libbluray --with-libbs2b --with-libbs2b --with-libopenmpt --with-librsvg --with-libsoxr --with-libssh --with-libvidstab --with-libvmaf --with-libxml2 --with-libzvbi --with-openssl --with-rav1e --with-rtmpdump --with-speex --with-srt --with-tesseract --with-two-lame --with-webp --with-xvid --with-zeromq --with-zimg`

`==> Installing homebrew-ffmpeg/ffmpeg/ffmpeg --with-fdk-aac --with-jack --with-libopenmpt --with-librsvg --with-libsoxr --with-libssh --with-tesseract --with-libvidstab --with-openssl --with-rav1e --with-rtmpdump --with-webp --with-zeromq --with-zimg --with-srt --with-libvmaf --with-libxml2 --with-libzvbi -
==> ./configure --prefix=/usr/local/Cellar/ffmpeg/5.0.1-with-options_2 --enable-shared --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libaom --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-libsnappy --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx26
Last 15 lines from /Users/vincentdabouineau/Library/Logs/Homebrew/ffmpeg/01.configure:
--enable-libzvbi
--enable-libzmq
--enable-openssl
--enable-nonfree
--enable-libjack
--enable-indev=jack
--enable-version3

ERROR: zvbi-0.2 not found using pkg-config

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.libera.chat.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/issues

These open issues may also help:
Brewing custom ffmpeg but failure at metal execution https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/issues/96`

`~$ffplay
zsh: command not found: ffplay`

**Comment by retokromer** [comment]
@Vincent-Dabouineau Sorry, I am not sure I understand this carefully. Our formula builds all three `ffmpeg`, `ffplay` and `ffprobe` commands. Could you elaborate please?

**Comment by Vincent-Dabouineau** [comment]
> @Vincent-Dabouineau Sorry, I am not sure I understand this carefully. Our formula builds all three `ffmpeg`, `ffplay` and `ffprobe` commands. Could you elaborate please?

Here it is within the original post just updated. Another issue with `libzvbi` for which we maybe need to install it via Homebrew first?

**Comment by slhck** [comment]
Yes, you need to install the dependency first. There does not seem to be a Homebrew-supplied Formula for it though, so you will have to install it manually. There is an (older) tap that uses its own Formula: https://github.com/johnwheeler/homebrew-ffmpeg-with-zvbi

The ffplay error you are describing is a consequence of the Formula not installing correctly.

**Comment by retokromer** [comment]
I added a note in https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/pull/108
