### ISSUE TITLE
Can't upgrade to 5.1

### ISSUE THREAD

**Issue by olikami** [homebrew-ffmpeg/homebrew-ffmpeg#116]
## Bug Reports

⚠️ **This is for bug reports with the `homebrew-ffmpeg` tap only.** Please do not file a bug report if your issue relates to any of the following:

- Homebrew itself (see the [brew](https://github.com/Homebrew/brew/) issue tracker or their [discussion forum](https://github.com/Homebrew/discussions/discussions))
- The `ffmpeg` formula officially supplied by Homebrew
- An error with ffmpeg itself (use [trac.ffmpeg.org](https://trac.ffmpeg.org/) to file a bug, or the [`ffmpeg-user` mailing list](https://ffmpeg.org/contact.html#MailingLists))

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information.**

- [X] I ran `brew update` and can still reproduce the problem
- [X] I ran `brew doctor`, fixed all issues and can still reproduce the problem
- [X] I ran `brew config` and `brew doctor` and included their output with my issue
- [X] I verified that this is an issue with *this* tap and not any other `ffmpeg` version

## Expected behavior

Run `brew upgrade` to install new version.

## Actual behavior

Upgrade failed:

```
==> Upgrading homebrew-ffmpeg/ffmpeg/ffmpeg
  5.0.1-with-options_5 -> 5.1-with-options --with-fdk-aac --with-game-music-emu --with-jack --with-libmodplug --with-libopenmpt --with-librist --with-librsvg --w
Error: An exception occurred within a child process:
  Utils::Inreplace::Error: inreplace failed
doc/filters.texi:
  expected replacement of "/usr/local/share/model" with #<Pathname:/opt/homebrew/share/libvmaf/model>
```

## Command

The exact command you were trying to run:

```
brew update; brew upgrade
```

The output that you got:

```
<add output here>
```

## Output of `brew config` and `brew doctor` commands

`brew config`:

```
HOMEBREW_VERSION: 3.5.6-28-g5080312
ORIGIN: https://github.com/Homebrew/brew
HEAD: 5080312bdd6abee6066291e3b3b7b3f15d249b64
Last commit: 9 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ee113d3a163a30b221df4994e08a883556de6111
Core tap last commit: 57 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ENV_HINTS: set
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.37.1 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.5-arm64
CLT: 13.4.0.0.1.1651278267
Xcode: 13.4.1
Rosetta 2: false
```

`brew doctor`:

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  ffmpeg
  docker
  numpy
  pillow
  libomp
```

**Comment by slhck** [comment]
Hm. Let me verify that on my Mac later on!

**Comment by retokromer** [comment]
@olikami Thank you for reporting! Do you have the full list of the `--with-` you have enabled? (The output above is truncated.)

**Comment by retokromer** [comment]
P.S. – For example `ffmpeg -version` gives the full configuration applied.

**Comment by olikami** [comment]
`--with-fdk-aac --with-game-music-emu --with-jack --with-libmodplug --with-libopenmpt --with-librist --with-librsvg --with-libsoxr --with-libssh --with-tesseract --with-libvidstab --with-opencore-amr --with-openh264 --with-openjpeg --with-openssl --with-rav1e --with-rtmpdump --with-rubberband --with-webp --with-zeromq --with-zimg --with-srt --with-libvmaf --with-libxml2 --with-libbluray --with-libbs2b --with-libcaca --with-libgsm --with-openssl@1.1 --with-speex --with-two-lame --with-xvid` according to `brew info` 

I believe `--with-libvmaf` is the offending option

**Comment by retokromer** [comment]
Yep:
https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/blob/e5140d3affc484e9e5d5ae9ba6227f6da18a714e/Formula/ffmpeg.rb#L193-L200

**Comment by retokromer** [comment]
If you delete that block, does it work on your end, @olikami? (Sorry, I cannot test it before Tuesday…)

**Comment by olikami** [comment]
Yeah that does the trick.

**Comment by retokromer** [comment]
OK, thank you!

**Comment by slhck** [comment]
See also https://github.com/Homebrew/homebrew-core/pull/106412 where the same issue is being discussed. Have to check if vmaf is working though with these replacements.

**Comment by slhck** [comment]
Should be resolved with the latest revision! (It builds and runs VMAF on my end.)
