### ISSUE TITLE
zmq not working

### ISSUE THREAD

**Issue by steeley** [homebrew-ffmpeg/homebrew-ffmpeg#12]
using this example from the ffmpeg doc:
ffmpeg -re -i input -f mpegts zmq:tcp://127.0.0.1:5555

just produces the error:
zmq:tcp://127.0.0.1:5555: Protocol not found

running brew on OSX 10.13.6
brew did install the option:
ffmpeg version 4.2.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with Apple LLVM version 10.0.0 (clang-1000.10.44.4)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.2.1-with-options_2 --enable-shared --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libaom --enable-libmp3lame --enable-libopus --enable-libsnappy --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --disable-libjack --disable-indev=jack --enable-opencl --enable-videotoolbox --disable-htmlpages --enable-libzmq
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100

**Comment by retokromer** [comment]
In order to compile FFmpeg with the `libzmq` library, you have to pass the flag `--with-zeromq`.

**Comment by steeley** [comment]
Yes, thats exactly what I did as explained in my post.
    On Sunday, 17 November 2019, 10:49:24 GMT, Reto Kromer <notifications@github.com> wrote:  
 
 
In order to compile FFmpeg with the libzmq library, you have to pass the flag --with-zeromq.

**Comment by retokromer** [comment]
Yep, I’ve seen immediately after having answered (`--enable-libzmq`), therefore I deleted the useless message.

I cannot reproduce the error on my laptop, and I’m currently travelling.

**Comment by retokromer** [comment]
@steeley Could you possibly test if the current HEAD works on your end?

**Comment by steeley** [comment]
not using zmq or ffmpeg
