### ISSUE TITLE
FFmpeg 6.0

### ISSUE THREAD

**Issue by nhubbard** [homebrew-ffmpeg/homebrew-ffmpeg#123]
## Is your feature request related to a problem? Please describe.

FFmpeg 6.0 "Von Neumann" has been released.

## Describe the solution you'd like

I would like to update to 6.0 at some point in the near future. Is there a defined process for updating this tap to the latest upstream version?

## Describe alternatives you've considered

I haven't tried any alternatives yet, because it's the only way that I install FFmpeg on macOS.

**Comment by slhck** [comment]
There's an open PR but it's failing CI. 6.0 isn't even on Homebrew yet so please bear with us a little more.

**Comment by retokromer** [comment]
@nhubbard see https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/pull/122

**Comment by slhck** [comment]
@nhubbard This is now merged.

**Comment by nhubbard** [comment]
This is what I get when I don't drink my coffee on time! Thanks for your kindness about my mistake :)
