### ISSUE TITLE
"unpaper" won't run without ffmpeg 5.x

### ISSUE THREAD

**Issue by ghost** [homebrew-ffmpeg/homebrew-ffmpeg#126]
Hello,

I use both a utility called "unpaper" (for turning scans into PDF) and your unofficial "ffmpeg" (for audio and video)."unpaper" depends on the official "ffmpeg", so I use the trick described here:

https://github.com/homebrew-ffmpeg/homebrew-ffmpeg#troubleshooting

to circumvent this dependency. This has always worked for years until now. However, after I did the latest update of Homebrew and the formulas today, "unpaper" won't run anymore. It says:

```
% unpaper 
dyld[35533]: Library not loaded: /usr/local/opt/ffmpeg/lib/libavformat.59.dylib
  Referenced from: <A1443G1M-27DD-2980-AFBB-3846C04B7FGG> /usr/local/Cellar/unpaper/7.0.0/bin/unpaper
  Reason: tried: '/usr/local/opt/ffmpeg/lib/libavformat.59.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/ffmpeg/lib/libavformat.59.dylib' (no such file), '/usr/local/opt/ffmpeg/lib/libavformat.59.dylib' (no such file), '/usr/local/lib/libavformat.59.dylib' (no such file), '/usr/lib/libavformat.59.dylib' (no such file, not in dyld cache), '/usr/local/Cellar/ffmpeg/6.0-with-options/lib/libavformat.59.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/Cellar/ffmpeg/6.0-with-options/lib/libavformat.59.dylib' (no such file), '/usr/local/Cellar/ffmpeg/6.0-with-options/lib/libavformat.59.dylib' (no such file), '/usr/local/lib/libavformat.59.dylib' (no such file), '/usr/lib/libavformat.59.dylib' (no such file, not in dyld cache)
zsh: abort      unpaper
```
My understanding from all those messages (correct me if I'm wrong) is that "unpaper" is looking for version 5.x, but your unofficial "ffmpeg" has since moved to version 6.

Here is the DYLIB files on my computer:

```
% ls -1 /usr/local/opt/ffmpeg/lib/
libavcodec.60.3.100.dylib
libavcodec.60.dylib
libavcodec.a
libavcodec.dylib
libavdevice.60.1.100.dylib
libavdevice.60.dylib
libavdevice.a
libavdevice.dylib
libavfilter.9.3.100.dylib
libavfilter.9.dylib
libavfilter.a
libavfilter.dylib
libavformat.60.3.100.dylib
libavformat.60.dylib
libavformat.a
libavformat.dylib
libavutil.58.2.100.dylib
libavutil.58.dylib
libavutil.a
libavutil.dylib
libpostproc.57.1.100.dylib
libpostproc.57.dylib
libpostproc.a
libpostproc.dylib
libswresample.4.10.100.dylib
libswresample.4.dylib
libswresample.a
libswresample.dylib
libswscale.7.1.100.dylib
libswscale.7.dylib
libswscale.a
libswscale.dylib
pkgconfig
```

In this scenario, how can I make coexist "unpaper" and your unofficial "ffmpeg"?

**Comment by slhck** [comment]
Can you try reinstalling `unpaper`? It could just be that it can no longer find the libraries it linked against initially.

An alternative might be installing `ffmpeg@5` from official Homebrew.

Or you can try to get `unpaper` authors to make it work with the existing installation. I have not looked at how unpaper does this though.

**Comment by slhck** [comment]
Please feel free to leave it open to track it. 

I personally am at least not aware of a direct solution. I don't think it should take long for Homebrew to upgrade the ffmpeg formula.

Another alternative might be installing a previous commit of this alternative formula. I'm not sure if Homebrew supports that, but the formula is just a file on the system and it's a git repository, so it could be possible to just downgrade it on your machine for the time being.

I'm just not on a computer so I can't help immediately.

**Comment by slhck** [comment]
Sure! I hope it will resolve itself once Homebrew bumps the version. (And in fact I can think of the opposite problem if the other tap does not bump to 6.0 simultaneously...)

**Comment by retokromer** [comment]
The Homebrew own FFmpeg formula does often need longer, because of all the related formulae which need to be bumped. We prefer to make available the new versions as they are released. This is why.
