### ISSUE TITLE
Add `libplacebo` as a supported (optional) library

### ISSUE THREAD

**Issue by ahobsonsayers** [homebrew-ffmpeg/homebrew-ffmpeg#128]
FFmpeg now has support for the [libplacebo](https://github.com/haasn/libplacebo) filter. Therefore i was hoping it might be possible to get `libplacebo` (`--enable-libplacebo`) included as one of the optional libraries? As part of this i think vulkan would need to be optionally enabled via `--enable-vulkan`

Thoughts on this?

**Comment by slhck** [comment]
Good suggestion!

I *think* we still have to wait until ffmpeg 6.0 is out on Homebrew core, because `libplacebo` there still depends on ffmpeg 5.x. This is the open PR: https://github.com/Homebrew/homebrew-core/pull/124363

**Comment by ahobsonsayers** [comment]
Interestingly,I was looking at the formula for libplacebo today and I'm actually unsure why ffmpeg is a dependency. Certainly it is not according to the libplacebo readme. I also tried forking and installing it without ffmpeg as a dependency and it seems to work fine.

I was actually considering opening a PR over there, cos I can only deduct it was included as a dependency by mistake.

**Comment by slhck** [comment]
Yeah, you're right — thinking about it, it should be the other way around.

**Comment by retokromer** [comment]
Thank you @ahobsonsayers for the suggestion! Unless you open a PR before, possibly I can do it on Friday.

**Comment by retokromer** [comment]
@ahobsonsayers : I have prepared a [PR](https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/pull/129 which should implement your suggestion), but I suggest to wait until your PR on Homebrew is done.

**Comment by ahobsonsayers** [comment]
@retokromer this is awesome! Thanks! You got on that amazingly quickly ☺️

**Comment by ahobsonsayers** [comment]
So I have created a [PR](https://github.com/Homebrew/homebrew-core/pull/126408) to try and fix the libplacebo homebrew formula, however I am having problems getting it to work. If I'm honest I am a bit out of my depth as my background is not c++ and I have no experience in its toolchain or homebrews ecosystem for that matter.

Don't suppose anyone has any advice?

**Comment by bbgdzxng1** [comment]
@ahobsonsayers, recent work on libplacebo in https://github.com/Homebrew/homebrew-core/pull/153961 may help - there have been a few changes to libplacebo regarding shaderc/glslang and removing sdl2 as a dependency for plplay.  Furthermore, it may be worth revisiting now that FFmpeg 6.1 is out.  I'm too stupid to fully understand the implications, but it looks like there has been some housekeeping which may now clear upstream dependencies.  Please ignore (or thumbs down) if this comment is irrelevant.  Thanks for everyone's efforts in trying to get libplacebo into the homebrew-ffmpeg tap.

**Comment by ahobsonsayers** [comment]
@bbgdzxng1 thanks for the ping. I had been following the progress of that PR but hadn't noticed it had been merged. I'll see if I can have another look at it this weekend and hopefully update this PR to get it all working!

**Comment by retokromer** [comment]
Done in https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/pull/160
