### ISSUE TITLE
Patch failure for libavcodec when re-installing ffmpeg HEAD

### ISSUE THREAD

**Issue by loshlee** [homebrew-ffmpeg/homebrew-ffmpeg#137]
## Bug Reports

⚠️ **This is for bug reports with the `homebrew-ffmpeg` tap only.** Please do not file a bug report if your issue relates to any of the following:

- Homebrew itself (see the [brew](https://github.com/Homebrew/brew/) issue tracker or their [discussion forum](https://github.com/Homebrew/discussions/discussions))
- The `ffmpeg` formula officially supplied by Homebrew
- An error with ffmpeg itself (use [trac.ffmpeg.org](https://trac.ffmpeg.org/) to file a bug, or the [`ffmpeg-user` mailing list](https://ffmpeg.org/contact.html#MailingLists))

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information.**

- [√ ] I ran `brew update` and can still reproduce the problem
- [√ ] I ran `brew doctor`, fixed all issues and can still reproduce the problem
- [ √] I ran `brew config` and `brew doctor` and included their output with my issue
- [√ ] I verified that this is an issue with *this* tap and not any other `ffmpeg` version

## Expected behavior

HEAD re-installation of ffmpeg

## Command

```
brew reinstall homebrew-ffmpeg/ffmpeg/ffmpeg --HEAD
```

The output that you got:

```
==> Fetching homebrew-ffmpeg/ffmpeg/ffmpeg
==> Downloading https://git.videolan.org/?p=ffmpeg.git;a=patch;h=effadce6c756247ea8bae32dc13bb3e6f464f0eb
Already downloaded: ~/Library/Caches/Homebrew/downloads/5d13894c894ed65597383350d4613f01ea4d037ee14e67c04ade747e80efa231--ffmpeg.git-effadce6c756247ea8bae32dc13bb3e6f464f0eb.patch
==> Cloning https://github.com/FFmpeg/FFmpeg.git
Updating ~/Library/Caches/Homebrew/ffmpeg--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at aea2d269db configure: Include objbase.h when checking for CoTaskMemFree
==> Installing ffmpeg from homebrew-ffmpeg/ffmpeg
==> Patching
==> Applying ffmpeg.git-effadce6c756247ea8bae32dc13bb3e6f464f0eb.patch
patching file 'libavcodec/x86/mathops.h'
2 out of 2 hunks failed--saving rejects to 'libavcodec/x86/mathops.h.rej'
```

## Output of `brew config` and `brew doctor` commands

`brew config`:

```
HOMEBREW_VERSION: 4.1.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3cd72905ce3d36a84994cc6c6b9ebbdafff4e922
Last commit: 4 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ecdb4a1426acf9496cff6549122695598fdeb949
Core tap last commit: 3 hours ago
Core tap branch: master
Core tap JSON: 22 Aug 07:10 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.9qgSezAeyC/org.xquartz:0
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_INSTALL_FROM_API: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5.1-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: N/A
Rosetta 2: false
```

`brew doctor`:

```
Your system is ready to brew.
```

**Comment by slhck** [comment]
Does it work if you leave out the HEAD option? In that case we should make the patch dependent on the presence of the HEAD flag.

**Comment by loshlee** [comment]
Yes, installs successfully without HEAD.

**Comment by retokromer** [comment]
Exact same behaviour also occurs for the official formula, therefore it’s not a problem related to this formula.

**Comment by retokromer** [comment]
@loshlee You could open an issue at https://github.com/Homebrew/homebrew-core

**Comment by loshlee** [comment]
Thanks.

**Comment by loshlee** [comment]
Opened issue at "https://github.com/Homebrew/homebrew-core/issues/140182".

**Comment by retokromer** [comment]
Thank you, @loshlee !
