### ISSUE TITLE
libavdevice build error (Mac M1 Silicon)

### ISSUE THREAD

**Issue by loshlee** [homebrew-ffmpeg/homebrew-ffmpeg#140]
## Bug Reports

⚠️ **This is for bug reports with the `homebrew-ffmpeg` tap only.** Please do not file a bug report if your issue relates to any of the following:

- Homebrew itself (see the [brew](https://github.com/Homebrew/brew/) issue tracker or their [discussion forum](https://github.com/Homebrew/discussions/discussions))
- The `ffmpeg` formula officially supplied by Homebrew
- An error with ffmpeg itself (use [trac.ffmpeg.org](https://trac.ffmpeg.org/) to file a bug, or the [`ffmpeg-user` mailing list](https://ffmpeg.org/contact.html#MailingLists))

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information.**

- [√ ] I ran `brew update` and can still reproduce the problem
- [ √] I ran `brew doctor`, fixed all issues and can still reproduce the problem
- [ √] I ran `brew config` and `brew doctor` and included their output with my issue
- [ √] I verified that this is an issue with *this* tap and not any other `ffmpeg` version

## Expected behavior

Successful reinstallation of ffmpeg
## Actual behavior
Tried my usual: brew reinstall homebrew-ffmpeg/ffmpeg/ffmpeg (with options)

What happened?

## Command
[make install
...
make: *** Waiting for unfinished jobs....](ld: building exports trie: duplicate symbol '_av_ac3_parse_header')]

The exact command you were trying to run:

```
<enter command here>
brew reinstall homebrew-ffmpeg/ffmpeg/ffmpeg --with-chromaprint --with-fdk-aac --with-game-music-emu --with-jack --with-libbluray --with-libbs2b --with-libcaca --with-libgsm --with-libmodplug --with-libsoxr --with-libssh --with-libvidstab --with-opencore-amr --with-openh264 --with-openjpeg --with-openssl --with-rtmpdump --with-rubberband --with-speex --with-tesseract --with-two-lame --with-webp --with-xvid --with-zeromq --with-zimg
```

The output that you got:

<add output here>

make install
Last 15 lines from /Users/me/Library/Logs/Homebrew/ffmpeg/02.make:
INSTALL	libswresample/libswresample.dylib
STRIP	install-libswresample-shared
LD	libavformat/libavformat.60.dylib
INSTALL	libavcodec/libavcodec.dylib
STRIP	install-libavcodec-shared
LD	libavfilter/libavfilter.9.dylib
INSTALL	libavformat/libavformat.dylib
STRIP	install-libavformat-shared
LD	libavdevice/libavdevice.60.dylib
INSTALL	libavfilter/libavfilter.dylib
STRIP	install-libavfilter-shared
ld: building exports trie: duplicate symbol '_av_ac3_parse_header'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libavdevice/libavdevice.60.dylib] Error 1
make: *** Waiting for unfinished jobs....

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/issues
```

## Output of `brew config` and `brew doctor` commands


`brew config`:


<add output here>
HOMEBREW_VERSION: 4.1.12
ORIGIN: https://github.com/Homebrew/brew
HEAD: aa2a77b1f1ac1539e69e186bad1d569100448987
Last commit: 6 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 41d589f984c0db7dbc3badafa254bb721dcad4ef
Core tap last commit: 73 minutes ago
Core tap branch: master
Core tap JSON: 22 Sep 20:01 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.PbrnR1c9Ha/org.xquartz:0
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.6-arm64
CLT: 15.0.0.0.1.1694021235
Xcode: N/A
Rosetta 2: false

`brew doctor`:

<add output here>
Your system is ready to brew.

When I removed the old ffmpeg using "brew uninstall --ignore-dependencies ffmpeg", then "brew install ffmpeg" worked. It's apparently the specified build options (shown above), that causes the problem. Not completely sure this is the place to request help, but I'm trying to follow the build failure guidelines. Please advise if it isn't. Thanks.

**Comment by retokromer** [comment]
@loshlee Thank you for reporting! I cannot test now on macOS 13.6, but will do it in approximately one week time.

**Comment by slhck** [comment]
I can reproduce this on 13.5.2 on a M1 machine.

```
➜ brew reinstall homebrew-ffmpeg/ffmpeg/ffmpeg --with-chromaprint --with-fdk-aac --with-game-music-emu --with-jack --with-libbluray --with-libbs2b --with-libcaca --with-libgsm --with-libmodplug --with-libsoxr --with-libssh --with-libvidstab --with-opencore-amr --with-openh264 --with-openjpeg --with-openssl --with-rtmpdump --with-rubberband --with-speex --with-tesseract --with-two-lame --with-webp --with-xvid --with-zeromq --with-zimg

==> Fetching homebrew-ffmpeg/ffmpeg/ffmpeg
==> Downloading https://github.com/FFmpeg/FFmpeg/commit/effadce6c756247ea8bae32dc13bb3e6f464f0eb.patch?full_index=1
Already downloaded: /Users/werner/Library/Caches/Homebrew/downloads/a69d9379ef65ead2df9b7bcdd51b88390155ebe749aad80abb09ec661c242f0b--effadce6c756247ea8bae32dc13bb3e6f464f0eb.patch
==> Downloading https://gitlab.archlinux.org/archlinux/packaging/packages/ffmpeg/-/raw/5670ccd86d3b816f49ebc18cab878125eca2f81f/add-av_stream_get_first_dts-for-chromium.patch
Already downloaded: /Users/werner/Library/Caches/Homebrew/downloads/89c5a789bbb2e059f601e58af1ca10f4db2a1939f591f896a0240cb1cfb2b8bb--add-av_stream_get_first_dts-for-chromium.patch
==> Downloading https://ffmpeg.org/releases/ffmpeg-6.0.tar.xz
Already downloaded: /Users/werner/Library/Caches/Homebrew/downloads/cde06afa988dec3565a51f2a2b503db685b5a78ba8ecc7f3c95562c750a9d838--ffmpeg-6.0.tar.xz
==> Reinstalling homebrew-ffmpeg/ffmpeg/ffmpeg --with-chromaprint --with-fdk-aac --with-game-music-emu --with-jack --with-libmodplug --with-libsoxr --with-libssh --with-tesserac
==> Patching
==> Applying effadce6c756247ea8bae32dc13bb3e6f464f0eb.patch
patching file 'libavcodec/x86/mathops.h'
==> Applying add-av_stream_get_first_dts-for-chromium.patch
patching file 'libavformat/avformat.h'
patching file 'libavformat/mux_utils.c'
==> ./configure --enable-shared --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libaom --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-libsnappy --enable-l
==> make install
Last 15 lines from /Users/werner/Library/Logs/Homebrew/ffmpeg/02.make:
INSTALL	libavformat/libavformat.dylib
STRIP	install-libavformat-shared
CC	libavfilter/metal/vf_yadif_videotoolbox.metallib.o
GEN	libavfilter/libavfilter.ver
AR	libavfilter/libavfilter.a
LD	libavfilter/libavfilter.9.dylib
INSTALL	libavfilter/libavfilter.a
LD	libavdevice/libavdevice.60.dylib
INSTALL	libavfilter/libavfilter.dylib
STRIP	install-libavfilter-shared
ld: building exports trie: duplicate symbol '_av_ac3_parse_header'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libavdevice/libavdevice.60.dylib] Error 1
make: *** Waiting for unfinished jobs....
rm libavfilter/metal/vf_yadif_videotoolbox.metal.air libavfilter/metal/vf_yadif_videotoolbox.metallib libavfilter/metal/vf_yadif_videotoolbox.metallib.c
```

**Comment by slhck** [comment]
It also fails without any options, so these aren't causing the problem.

Someone mentions on a forum that this Formula gives the same error: https://github.com/apple/homebrew-apple/blob/main/Formula/game-porting-toolkit.rb — this does not have a lot in common with our formula.

**Comment by retokromer** [comment]
@loshlee Could you possibly test is the fix by @slhck solves your issue?

**Comment by slhck** [comment]
@retokromer The PR does not fix this, it just fixed a related issue attempting to run the command from @loshlee. So I'm reopening now...

**Comment by retokromer** [comment]
Oh, sorry @slhck, for the noise.

**Comment by retokromer** [comment]
>It also fails without any options, so these aren't causing the problem.

It seems to be related to clang 15.

**Comment by loshlee** [comment]
My workaround has been to use "brew uninstall --ignore-dependencies ffmpeg", then use "brew install ffmpeg".

**Comment by retokromer** [comment]
@loshlee Thank you for the information. I assume you are installing the standard Homebrew ffmpeg formula, but I would like to fix this one.

**Comment by sourcecodemage** [comment]
Same here while trying install ffmpeg with "--enable-libfdk-aac" .
M1 Macbook running macOS v13.5.2

`> brew update
Already up-to-date.

> brew doctor
Your system is ready to brew.

> brew config
HOMEBREW_VERSION: 4.1.12
ORIGIN: https://github.com/Homebrew/brew
HEAD: aa2a77b1f1ac1539e69e186bad1d569100448987
Last commit: 8 days ago
Core tap JSON: 24 Sep 18:00 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.42.0 => /opt/homebrew/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5.2-arm64
CLT: 15.0.0.0.1.1694021235
Xcode: 15.0
Rosetta 2: false

> brew uninstall --ignore-dependencies ffmpeg
Error: No such keg: /opt/homebrew/Cellar/ffmpeg

>brew install homebrew-ffmpeg/ffmpeg/ffmpeg --with-fdk-aac
/Users/redacted/Library/Logs/Homebrew/ffmpeg/02.make file attached since it's a lot of output.
extension changed to .txt to enable upload.
`

[02.make.txt](https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/files/12709313/02.make.txt)

**Comment by retokromer** [comment]
>It also fails without any options, so these aren't causing the problem.

The relevant lines are always the same:

```sh
LD	libavdevice/libavdevice.60.dylib
INSTALL	libavfilter/libavfilter.dylib
STRIP	install-libavfilter-shared
ld: building exports trie: duplicate symbol '_av_ac3_parse_header'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libavdevice/libavdevice.60.dylib] Error 1
```

**Comment by freultwah** [comment]
This is apparently an Xcode issue introduced in Xcode 15 beta 3: https://developer.apple.com/forums/thread/733317. I had the same issue with `ld: building exports trie: duplicate symbol '_av_ac3_parse_header'` and reverting to Xcode Command Line Tools 15b2 made stuff work.

**Comment by slhck** [comment]
Hmm. I have Xcode Version 15.0 (15A240d) and have this issue.

**Comment by freultwah** [comment]
It's apparently broken from 15b3 onwards, still not fixed even in the release.

**Comment by retokromer** [comment]
I don’t have Xcode on this machine and CLT (15.0.0.0.1.1694021235) also is broken.

**Comment by petersteneteg** [comment]
related PR from spack with a potential fix https://github.com/spack/spack/pull/40187

**Comment by fxcoudert** [comment]
This is a workaround, but Apple will need to fix their linker. Has the issue been reported to Apple? If so, what is the FB number?

**Comment by slhck** [comment]
Please test again, I could confirm it working now with the fix from @retokromer

**Comment by Moulick** [comment]
works now

**Comment by loshlee** [comment]
Thanks, everyone.

**Comment by sourcecodemage** [comment]
What is the work around, as in , what commands do I need to run ? Should I run brew update && brew upgrade && brew install homebrew-ffmpeg/ffmpeg/ffmpeg --with-fdk-aac ?

**Comment by loshlee** [comment]
Hard to be sure without more information. If your last successful initial installation included "--with-fdk-aac", and you haven't used other offhand attempts at workarounds and/or installation, I think this might suffice:

brew reinstall homebrew-ffmpeg/ffmpeg/ffmpeg

If you don't see "--with-fdk-aac"  in the output of that command, then installation with that option may require other steps. Anyway, that's what worked for me (I had previously also used "--HEAD").

**Comment by retokromer** [comment]
There is no workaround: just use the [regular installation](https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/blob/master/README.md). And if you get an error, please open a [new issue](https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/issues/new/choose), providing all the requested information.

**Comment by slhck** [comment]
With

```
➜ clang --version                                     
Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: arm64-apple-darwin23.4.0
```

I no longer need the workaround. It's stll version 15 though. Xcode 15.3.

Reopening so we can see if this can be removed or at least conditionally removed.
