### ISSUE TITLE
libvidstab error, failed on the 2nd pass, "Cannot parse localmotion"

### ISSUE THREAD

**Issue by sufehmi** [homebrew-ffmpeg/homebrew-ffmpeg#144]
Hi, 

I was trying to stabilize the video from my dashcam, but 2nd pass of vidstab always fail with error message "Cannot parse localmotion"

Googling around, I found this: [https://github.com/georgmartius/vid.stab/issues/104#issuecomment-734711275](https://github.com/georgmartius/vid.stab/issues/104#issuecomment-734711275 )

Turned out on Nov 27 2020, the maintainer of libvidstab merged a patch that cause ffmpeg to default to binary fileformat for libvidstab instead of ASCII fileformat.

And there's no option to specify the fileformat, so ffmpeg kept using the faulty binary fileformat, and libvidstab kept failing on the 2nd pass.

Here's the details of the installed ffmpeg :

`ffmpeg version 6.0 Copyright (c) 2000-2023 the FFmpeg developers
  built with Apple clang version 14.0.3 (clang-1403.0.22.14.1)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/6.0_1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon
`

FYI.

Thank you.

**Comment by retokromer** [comment]
Sorry, this issue is not related to our formula and should be resolved upstream. Here we do not maintain `libvidstab`, but “only” an alternate Homebrew formula to install FFmpeg.

**Comment by sufehmi** [comment]
Exactly, I thought you can , for example, use an earlier version on libvidstab instead, change the default fileformat to ASCII instead of binary, etc.

But thanks anyway.

**Comment by slhck** [comment]
We don't require specific versions, instead pointing to the most recently available versions from Homebrew Core formulae.

This all sounds to me like it requires fixes (or features) upstream in ffmpeg and/or libvidstab, after which they'd automatically become available here.
