### ISSUE TITLE
tap comparison

### ISSUE THREAD

**Issue by exekutive** [homebrew-ffmpeg/homebrew-ffmpeg#159]
This alternative ffmpeg tap supports the most options, if anybody was wondering.
(✔=default, O=option, ✘=not available)

| skyzyx | sydneys | justinmayer | retokromer | option         | descr                                                                  |
| ------ | ------- | ----------- | ---------- | -------------- | ---------------------------------------------------------------------- |
| ✔      | O       | ✔           | ✔          | aom            | Build with aom support                                                 |
| ✘      | O       | ✘           | O          | aribb24        | Build with aribb24 support                                             |
| ✘      | O       | O           | O          | chromaprint    | Enable the Chromaprint audio fingerprinting library                    |
| ✘      | O       | O           | O          | decklink       | Enable DeckLink support                                                |
| ✔      | O       | O           | O          | fdk-aac        | Enable the Fraunhofer FDK AAC library                                  |
| ✘      | O       | O           | O          | game-music-emu | Enable Game Music Emu (GME) support                                    |
| ✘      | ✘       | ✘           | O          | harfbuzz       | Enable OpenType text shaping engine                                    |
| ✘      | O       | O           | O          | jack           | Enable Jack support                                                    |
| ✘      | ✘       | ✘           | O          | jpeg-xl        | Enable JPEG XL image format                                            |
| ✔      | O       | ✔           | ✔          | libaom         | Enable libaom AV1 encoder library                                      |
| ✘      | O       | ✘           | O          | libaribb24     | Enable decoding ARIB/ISDB captions                                     |
| ✘      | ✘       | ✘           | O          | libaribcaption | Enable ARIB STD-B24 based broadcast captions                           |
| ✔      | O       | O           | O          | libbluray      | Build with libbluray support                                           |
| ✘      | O       | O           | O          | libbs2b        | Build with libbs2b support                                             |
| ✘      | O       | O           | O          | libcaca        | Build with libcaca support                                             |
| ✘      | ✘       | ✘           | O          | libflite       | Enable text to speech synthesis support via Flite                      |
| ✔      | O       | O           | O          | libgsm         | Build with libgsm support                                              |
| ✔      | O       | O           | O          | libmodplug     | Enable module/tracker files as inputs via libmodplug                   |
| ✘      | O       | ✘           | O          | libopenmpt     | Enable module/tracker files as inputs via libopenmpt                   |
| ✘      | O       | ✘           | O          | librist        | Enable Reliable Internet Stream Transport (RIST) support               |
| ✔      | O       | O           | O          | librsvg        | Enable SVG files as inputs via librsvg                                 |
| ✔      | O       | O           | O          | libsoxr        | Enable the soxr resample library                                       |
| ✘      | O       | O           | O          | libssh         | Enable SFTP protocol via libssh                                        |
| ✔      | O       | O           | O          | libvidstab     | Enable vid.stab support for video stabilization                        |
| ✘      | O       | O           | O          | libvmaf        | Enable libvmaf scoring library                                         |
| ✔      | O       | O           | O          | libxml2        | Enable libxml2 library                                                 |
| ✘      | O       | ✘           | O          | libzvbi        | Enable decoding of DVB teletext pages and DVB teletext subtitles       |
| ✔      | O       | O           | O          | opencore-amr   | Enable Opencore AMR NR/WB audio format                                 |
| ✔      | O       | O           | O          | openh264       | Enable OpenH264 library                                                |
| ✔      | O       | O           | O          | openjpeg       | Enable JPEG 2000 image format                                          |
| ✘      | O       | O           | O          | openssl        | Enable SSL support                                                     |
| ✘      | O       | O           | O          | openssl@1.1    | Build with openssl@1.1 support                                         |
| ✘      | ✘       | ✘           | O          | openvino       | Enable OpenVINO                                                        |
| ✘      | O       | O           | O          | rav1e          | Enable AV1 encoding via librav1e                                       |
| ✔      | O       | O           | O          | rtmpdump       | Enable RTMP dumping support                                            |
| ✔      | O       | O           | O          | rubberband     | Enable rubberband library                                              |
| ✔      | O       | O           | O          | speex          | Build with speex support                                               |
| ✔      | O       | O           | O          | srt            | Enable SRT library                                                     |
| ✔      | O       | ✘           | O          | svt-av1        | Enable Scalable Video Technology for AV1                               |
| ✔      | O       | O           | O          | tesseract      | Enable the tesseract OCR engine                                        |
| ✔      | O       | O           | O          | two-lame       | Enable TwoLAME an optimized MPEG Audio Layer 2 (MP2) encoder           |
| ✔      | O       | O           | O          | webp           | Enable using libwebp to encode WEBP images                             |
| ✔      | O       | O           | O          | xvid           | Enable Xvid                                                            |
| ✔      | O       | O           | O          | zeromq         | Enable using libzeromq to receive cmds sent through a libzeromq client |
| ✔      | O       | O           | O          | zimg           | Enable z.lib zimg library                                              |
| ✘      | O       | O           | O          | HEAD           | Install HEAD version                                                   |

**Comment by slhck** [comment]
Thanks for the info! Will close as not actionable.
