### ISSUE TITLE
cann't run ffmpeg in the terminal (mac m1, zsh)

### ISSUE THREAD

**Issue by peterjumper** [homebrew-ffmpeg/homebrew-ffmpeg#165]
## Bug Reports

⚠️ **This is for bug reports with the `homebrew-ffmpeg` tap only.** Please do not file a bug report if your issue relates to any of the following:

- Homebrew itself (see the [brew](https://github.com/Homebrew/brew/) issue tracker or their [discussion forum](https://github.com/Homebrew/discussions/discussions))
- The `ffmpeg` formula officially supplied by Homebrew
- An error with ffmpeg itself (use [trac.ffmpeg.org](https://trac.ffmpeg.org/) to file a bug, or the [`ffmpeg-user` mailing list](https://ffmpeg.org/contact.html#MailingLists))

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information.**

- [x] I ran `brew update` and can still reproduce the problem
- [x] I ran `brew doctor`, fixed all issues and can still reproduce the problem
- [x] I ran `brew config` and `brew doctor` and included their output with my issue
- [x] I verified that this is an issue with *this* tap and not any other `ffmpeg` version

## Expected behavior

![Screenshot 2024-07-14 at 1 44 36 AM](https://github.com/user-attachments/assets/afd2ca9a-adf6-40e6-8964-fe7b5eb06cd2)
![Screenshot 2024-07-14 at 1 47 14 AM](https://github.com/user-attachments/assets/0dbe5aea-3d83-4b14-8061-ddae5c244b30)
![Screenshot 2024-07-14 at 1 47 22 AM](https://github.com/user-attachments/assets/21fbddf2-a777-4030-96e6-520fc81285e4)

## Actual behavior

What happened?

can't install ffmpeg ......  i don't know what happen , fk mac os path 

undated my os, reinstall xcode, => install xcode whole app => still can't figure it , i guess some path messed up so bad :(

tried brew bulild source, install ffmpeg --head
none of it works

Library/Frameworks/OpenGL.framework🔒 
❯ fd com.apple
Libraries
OpenGL
Resources
Versions/
Versions/A/
Versions/A/Libraries/
Versions/A/Libraries/3425AMD/
Versions/A/Libraries/3425AMD/CVMCompiler
Versions/A/Libraries/3425AMD/libCoreVMClient.mono.dylib
Versions/A/Libraries/3600/
Versions/A/Libraries/3600/CVMCompiler
Versions/A/Libraries/3600/libCoreVMClient.mono.dylib
Versions/A/Libraries/CVMCompiler
Versions/A/Libraries/CVMServer
Versions/A/Libraries/DumpGPURestart
Versions/A/Libraries/ReportGPURestart
Versions/A/Libraries/libGLVMPlugin.dylib
Versions/A/Libraries/libGLVMPlugin32023.dylib
Versions/A/Resources/
Versions/A/Resources/BridgeSupport/
Versions/A/Resources/BridgeSupport/OpenGL.arm64e.bridgesupport
Versions/A/Resources/BridgeSupport/OpenGL.bridgesupport
Versions/A/Resources/CVMSPlugin.exp
Versions/A/Resources/CVMSPluginAll.exp
Versions/A/Resources/CVMSPluginNoExec.exp
Versions/A/Resources/GLByteCodes.arm64.bc
Versions/A/Resources/GLByteCodes.x86_64.bc
Versions/A/Resources/GLEngine.bundle/
Versions/A/Resources/GLRendererFloat.bundle/
Versions/A/Resources/Info.plist
Versions/A/Resources/cvmsConfig.plist
Versions/A/Resources/version.plist
Versions/A/_CodeSignature/
Versions/A/_CodeSignature/CodeResources
Versions/Current

----

the true openGL path should be here i confirm:

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework

should i use something like ln -i / rsync to solve this problem 

without ffmpeg give me headache, please help me

## Command

The exact command you were trying to run:

```
ffmpeg 
```

The output that you got:

 Referenced from: <C9D2182C-1C62-39B8-8D53-5D1D4C549173> /opt/homebrew/Cellar/ffmpeg/HEAD-f1abb75/lib/libavfilter.10.2.102.dylib
  Expected in:     <15D7BA68-D6BA-302D-93BE-2D93B860F106> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL

```
<add output here>
```

## Output of `brew config` and `brew doctor` commands

`brew config`:
HOMEBREW_VERSION: 4.3.9-98-g0a7b61a
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0a7b61a0a9e50e0263f93e865bd921aa5d21e462
Last commit: 2 hours ago
Core tap HEAD: e5797379a517da052954dbe90b3abd4b2f1a108f
Core tap last commit: 2 hours ago
Core tap JSON: 13 Jul 16:38 UTC
Core cask tap JSON: 13 Jul 16:38 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.3 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.45.2 => /opt/homebrew/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.4
Rosetta 2: false

```
<add output here>
```

`brew doctor`:
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed casks are deprecated or disabled.
You should find replacements for the following casks:
  chrome-devtools

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  ciphey

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  ciphey
  cowsay
  gumbo-parser
  neofetch
  python-lxml
  python-packaging

Warning: You have the following deprecated, official taps tapped:
  Homebrew/homebrew-cask-fonts
Untap them with `brew untap`.

Warning: Putting non-prefixed coreutils in your path can cause GMP builds to fail.

Warning: Putting non-prefixed findutils in your path can cause python builds to fail.

```
<add output here>
```

**Comment by slhck** [comment]
Without being able to dig into this any further, please check that you do not overrided or set `DYLD_LIBRARY_PATH` anywhere in your shell profile/configuration files. Check `.zshrc` or `.zprofile` (or `.bashrc` and `.bash_profile`, if you are using bash).

**Comment by peterjumper** [comment]
❮ sudo ln -s  "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL.tbd" "/System/Library/Frameworks/OpenGL.framework/Versions/A"
ln: failed to create symbolic link '/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL.tbd': Read-only file system

damn this problem is hard, should i force replacing system library as gpt said?

sudo rm -rf /System/Library/Frameworks/OpenGL.framework
sudo mv /System/Library/Frameworks/OpenGL.framework.backup /System/Library/Frameworks/OpenGL.framework
sudo update_dyld_shared_cache
sudo reboot

```zshrc
ZIM_HOME=~/.config/zsh/zim
ZIM_CONFIG_FILE=~/.config/zsh/zimrc
export EDITOR=nvim
export XDG_CONFIG_HOME="$HOME/.config"
fpath=($HOME/.config/zsh/completion $fpath)
export JAVA_HOME=$(/usr/libexec/java_home -v 21.0.2)
export PATH=$JAVA_HOME/bin:$PATH
# export PATH="/Applications/MacPorts/Emacs.app/Contents/MacOS:$PATH"
HISTSIZE=1000000
SAVEHIST=1000000
autoload edit-command-line; zle -N edit-command-line
bindkey -M vicmd '^g' edit-command-line 
bindkey '^g' edit-command-line #vim mode
# autoload copy-earlier-word ; zle -N copy-earlier-word
bindkey "^[." insert-last-word
# bindkey -M vicmd "^o" copy-earlier-word
## brew 
eval "$(/opt/homebrew/bin/brew shellenv)"
# allow zoxide zz completion 
eval "$(zoxide init zsh)"

# luarocks config
eval "$(luarocks path --bin)"
# eval "$(starship init zsh)"

 ## seting up pyenv 
# export PYENV_ROOT="$HOME/.pyenv"
# export THEOS="$HOME/theos"
# [[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
# eval "$(pyenv init -)"
# eval "$(pyenv virtualenv-init -)"


function yy() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
	yazi "$@" --cwd-file="$tmp"
	if cwd="$(cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
		cd -- "$cwd"
	fi
	rm -f -- "$tmp"
}

# function ctrl_l() {
#     builtin print -rn -- $'\r\e[0J\e[H\e[22J' >"$TTY"
#     builtin zle .reset-prompt
#     builtin zle -R
# }
# zle -N ctrl_l
# bindkey -M viins "^l'" ctrl_l

function ct() {
    local selection=$(tag -f blue | sk)
    if [ -d "$selection" ]; then
        cd "$selection"
    elif [ -f "$selection" ]; then
        cd "$(dirname "$selection")"
        echo "Moved to directory containing $(basename "$selection")"
    else
        echo "Selected item is neither a file nor a directory"
    fi
}




if [[ ! "$PATH" == */opt/homebrew/opt/fzf/bin* ]]; then
  PATH="${PATH:+${PATH}:}/opt/homebrew/opt/fzf/bin"
fi

# Auto-completion
# ---------------
source "/opt/homebrew/opt/fzf/shell/completion.zsh"

# Key bindings
# ------------
source "/opt/homebrew/opt/fzf/shell/key-bindings.zsh"

## Personal file
source $HOME/.config/zsh/aliases.zsh
source $HOME/.config/zsh/exports.zsh


# export LANG="zh_TW.UTF-8"
# export LC_ALL="zh_TW.UTF-8"
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

case ":${PATH}:" in
    *:"$HOME/.cargo/bin":*)
        ;;
    *)
        # Prepending path in case a system-installed rustc needs to be overridden
        export PATH="$HOME/.cargo/bin:$PATH"
        ;;
esac






## fzf
export FZF_DEFAULT_COMMAND='rg --no-config --files --no-ignore --hidden --follow -g "!{.git,node_modules}/*" 2> /dev/null'
export FZF_DEFAULT_OPTS="-i -m --height 70% --layout=reverse --border --inline-info \
--bind 'ctrl-t:toggle-preview' \
--bind 'ctrl-o:become(nvim {+})' \
--bind 'ctrl-y:execute(echo {+} | pbcopy)+abort' \
--bind 'ctrl-a:toggle-all'  \
--bind 'ctrl-j:toggle+down'  \
--bind 'ctrl-k:toggle+up' \
--bind 'tab:down' \
--bind 'btab:up' \
--bind 'f12:execute(sioyek {})'" 

rga-fzf() {
	RG_PREFIX="rga --files-with-matches"
	local file
	file="$(
		FZF_DEFAULT_COMMAND="$RG_PREFIX '$1'" \
			fzf --sort --preview="[[ ! -z {} ]] && rga --pretty --context 3 {q} {}" \
				--phony -q "$1" \
				--bind "change:reload:$RG_PREFIX {q}" \
				--preview-window="70%:wrap"
	)" &&
	echo "opening $file" &&
	open "$file"
}

lfcd () {
    tmp="$(mktemp)"
    # `command` is needed in case `lfcd` is aliased to `lf`
    command lf -last-dir-path="$tmp" "$@"
    if [ -f "$tmp" ]; then
        dir="$(cat "$tmp")"
        rm -f "$tmp"
        if [ -d "$dir" ]; then
            if [ "$dir" != "$(pwd)" ]; then
                cd "$dir"
            fi
        fi
    fi
}




# replacing gnu
BREW_BIN="/usr/local/bin/brew"
if [ -f "/opt/homebrew/bin/brew" ]; then
   BREW_BIN="/opt/homebrew/bin/brew"
fi

if type "${BREW_BIN}" &> /dev/null; then
    export BREW_PREFIX="$("${BREW_BIN}" --prefix)"
    for bindir in "${BREW_PREFIX}/opt/"*"/libexec/gnubin"; do export PATH=$bindir:$PATH; done
    for bindir in "${BREW_PREFIX}/opt/"*"/bin"; do export PATH=$bindir:$PATH; done
    # for mandir in "${BREW_PREFIX}/opt/"*"/libexec/gnuman"; do export MANPATH=$mandir:$MANPATH; done
    # for mandir in "${BREW_PREFIX}/opt/"*"/share/man/man1"; do export MANPATH=$mandir:$MANPATH; done
fi



# ZIM_HOME=~/.config/zsh/zim
# ZIM_CONFIG_FILE=~/.config/zsh/zimrc

# Download zimfw plugin manager if missing.
if [[ ! -e ${ZIM_HOME}/zimfw.zsh ]]; then
  curl -fsSL --create-dirs -o ${ZIM_HOME}/zimfw.zsh \
      https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh
fi
# Download zimfw plugin manager if missing.
if [[ ! -e ${ZIM_HOME}/zimfw.zsh ]]; then
  mkdir -p ${ZIM_HOME} && wget -nv -O ${ZIM_HOME}/zimfw.zsh \
      https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh
fi
# Install missing modules, and update ${ZIM_HOME}/init.zsh if missing or outdated.
if [[ ! ${ZIM_HOME}/init.zsh -nt ${ZDOTDIR:-${HOME}}/.zimrc ]]; then
  source ${ZIM_HOME}/zimfw.zsh init -q
fi
# Initialize modules.
source ${ZIM_HOME}/init.zsh

# zstyle ':zim:zmodule' use 'git'
zstyle ':zim:zmodule' use 'git'


# To avoid them accidentally linking against a Pyenv-provided Python, add the following line into your interactive shell's configuration:

alias brew='env PATH="${PATH//$(pyenv root)\/shims:/}" brew'
eval "$(starship init zsh)"
if test "$TERM" = "xterm-kitty"; then
  if (( $+commands[kitty] )); then
    eval "$(kitty + complete setup zsh)"
  fi
fi


# adding below to make fzftab work
# autoload -U +X bashcompinit && bashcompinit
# autoload -U +X compinit && compinit
# export PATH="/opt/homebrew/opt/ffmpeg@6/bin:$PATH"
```

```zimrc
#zmodule asciiship
zstyle ':zim:zmodule' use 'git'
zmodule zsh-users/zsh-syntax-highlighting
# zmodule kiesman99/zim-zoxide
# zmodule zimfw/environment
zmodule zimfw/fzf
zmodule zsh-users/zsh-autosuggestions
zmodule zimfw/exa
zmodule zsh-users/zsh-completions --fpath src

# zmodule "lukechilds/zsh-nvm"
zmodule "hlissner/zsh-autopair"
export VI_MODE_ESC_INSERT="jk" && zmodule "zap-zsh/vim"
# Yank to the system clipboard
function vi-yank-xclip {
    zle vi-yank
   echo "$CUTBUFFER" | tr -d '\n' | pbcopy -i
}

zle -N vi-yank-xclip
bindkey -M vicmd 'y' vi-yank-xclip
bindkey -M vicmd -r '\ec' 
bindkey -M viins -r '\ec' 

zmodule joke/zim-mise ## mise control
zmodule joke/zim-yq 	
zmodule joke/zim-github-cli

# bindkey -M menuselect '^o' accept-and-infer-next-history
# bindkey -M menuselect 'h' vi-backward-char
# bindkey -M menuselect 'j' vi-down-line-or-history
# bindkey -M menuselect 'k' vi-up-line-or-history
# bindkey -M menuselect 'l' vi-forward-char
# bindkey -M viins "^['" quote-line
# bindkey -M viins "^[^e" globalias
# bindkey -M viins '^ ' set-mark-command
# bindkey -M viins '^/' undo
# bindkey -M viins '^["' quote-region
# bindkey -M viins '^[-' neg-argument
# bindkey -M viins '^[.' insert-last-word
# bindkey -M viins '^[<' beginning-of-buffer-or-history
# bindkey -M viins '^[>' end-of-buffer-or-history
# bindkey -M viins '^[^h' backward-kill-word
# bindkey -M viins '^[b' backward-word
# bindkey -M viins '^[c' capitalize-word
# bindkey -M viins '^[d' kill-word
# bindkey -M viins '^[f' forward-word
# bindkey -M viins '^[h' kill-region
# bindkey -M viins '^[l' down-case-word
# bindkey -M viins '^[n' history-search-forward
# bindkey -M viins '^[p' history-search-backward
# bindkey -M viins '^[t' transpose-words
# bindkey -M viins '^[u' up-case-word
# bindkey -M viins '^[w' copy-region-as-kill
# bindkey -M viins '^[x' execute-named-cmd
# bindkey -M viins '^[y' yank-pop
# bindkey -M viins '^_' undo
# bindkey -M viins '^a' beginning-of-line
# bindkey -M viins '^b' backward-char
# bindkey -M viins '^d' delete-char
# bindkey -M viins '^e' end-of-line
# bindkey -M viins '^f' forward-char
# bindkey -M viins '^g' send-break
# bindkey -M viins '^h' backward-delete-char
# bindkey -M viins '^k' kill-line
# bindkey -M viins '^n' down-history
# bindkey -M viins '^o' accept-line-and-down-history
# bindkey -M viins '^p' up-history
# bindkey -M viins '^r' fzf-history-widget
# bindkey -M viins '^t' transpose-chars
# bindkey -M viins '^u' backward-kill-line
# bindkey -M viins '^w' backward-kill-word
# bindkey -M viins '^x^a' fasd-complete
# bindkey -M viins '^x^b' vi-match-bracket
# bindkey -M viins '^x^d' fasd-complete-d
# bindkey -M viins '^x^e' edit-command-line
# bindkey -M viins '^x^f' fasd-complete-f
# bindkey -M viins '^x^j' fzf-cd-widget
# bindkey -M viins '^x^s' fzf-file-widget
# bindkey -M viins '^x^u' undo
# bindkey -M viins '^x^x' exchange-point-and-mark
# bindkey -M viins '^xa' fasd-complete
# bindkey -M viins '^xb' vi-match-bracket
# bindkey -M viins '^xd' fasd-complete-d
# bindkey -M viins '^xe' edit-command-line
# bindkey -M viins '^xf' fasd-complete-f
# bindkey -M viins '^xj' fzf-cd-widget
# bindkey -M viins '^xs' fzf-file-widget
# bindkey -M viins '^xu' undo
# bindkey -M viins '^xx' exchange-point-and-mark
# bindkey -M viins '^y' yank
# bindkey -M viins "∫" backward-word
# bindkey -M viins "ƒ" forward-word
# bindkey -M viins "∂" delete-word
# bindkey -M viins '˙' backward-kill-word
# bindkey -M viins '≥' insert-last-word


zmodule wintermi/zsh-fnm
zmodule MichaelAquilina/zsh-you-should-use


## must adding personal completion before zmodule completion
# zmodule zimfw/prompt-pwd ## requied by theme
# zmodule zimfw/git-info
# zmodule zimfw/duration-info
zmodule zimfw/magic-enter ## pretty imazing
# zmodule starship/starship
# zmodule spaceship-prompt/spaceship-prompt --name spaceship --no-submodules


# zmodule zimfw/sorin ## theme
# zmodule zimfw/asciiship
zmodule zimfw/utility ## zsh tips
zmodule zimfw/homebrew



#zmodule joke/zim-chezmoi 	
#zmodule joke/zim-gopass  # password
#zmodule joke/zim-helm 
#zmodule joke/zim-istioctl 	
#zmodule joke/zim-k9s 	
#zmodule joke/zim-kn 
#zmodule joke/zim-kubectl 	
#zmodule joke/zim-minikube
#zmodule joke/zim-skaffold 	
#zmodule joke/zim-steampipe 	# maybe useful

zmodule Aloxaf/fzf-tab
## making sure fzf-tab in the last 
zstyle ':fzf-tab:complete:*:*' fzf-flags --height=70% --preview-window=right:wrap
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'eza -1 --color=always $realpath'
# zstyle ':fzf-tab:*' fzf-bindings 'ctrl-j:accept' 'ctrl-a:toggle-all' 'tab:toggle+down' 'btab:toggle+up' 
zstyle ':fzf-tab:*' fzf-bindings 'ctrl-a:toggle-all' 'ctrl-j:toggle+down' 'ctrl-k:toggle+up' 
zstyle ':fzf-tab:complete:tldr:argument-1' fzf-preview 'tldr --color always $word'
# disable sort when completing `git checkout`
zstyle ':completion:*:git-checkout:*' sort false
# set descriptions format to enable group support
# NOTE: don't use escape sequences here, fzf-tab will ignore them
zstyle ':completion:*:descriptions' format '[%d]'
# set list-colors to enable filename colorizing
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
# force zsh not to show completion menu, which allows fzf-tab to capture the unambiguous prefix
zstyle ':completion:*' menu no
zstyle ':fzf-tab:*' switch-group '<' '>'



zmodule zsh-users/zsh-completions --fpath src
# zmodule completion
autoload -U +X bashcompinit && bashcompinit
autoload -U +X compinit && compinit

```

❮ sudo ln -sf "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A" "/System/Library/Frameworks/OpenGL.framework/Versions/A"
ln: failed to create symbolic link '/System/Library/Frameworks/OpenGL.framework/Versions/A/A': Read-only file system

**Comment by peterjumper** [comment]
is it becasueof this part: replacing all the command with gnu
```zsh
# replacing gnu
BREW_BIN="/usr/local/bin/brew"
if [ -f "/opt/homebrew/bin/brew" ]; then
   BREW_BIN="/opt/homebrew/bin/brew"
fi

if type "${BREW_BIN}" &> /dev/null; then
    export BREW_PREFIX="$("${BREW_BIN}" --prefix)"
    for bindir in "${BREW_PREFIX}/opt/"*"/libexec/gnubin"; do export PATH=$bindir:$PATH; done
    for bindir in "${BREW_PREFIX}/opt/"*"/bin"; do export PATH=$bindir:$PATH; done
    # for mandir in "${BREW_PREFIX}/opt/"*"/libexec/gnuman"; do export MANPATH=$mandir:$MANPATH; done
    # for mandir in "${BREW_PREFIX}/opt/"*"/share/man/man1"; do export MANPATH=$mandir:$MANPATH; done
fi
```

**Comment by slhck** [comment]
It appears you are trying to forcibly delete a system library (which isn't possible under macOS due to SIP), and that you are copy-pasting commands that ChatGPT gave you without understanding their consequences.

Generally, you seem to just be dumping a lot of content here without even responding to my initial question/suggestion. Please consider that we maintain this tap in our spare time and have limited capacity to troubleshoot problems like this.

**Comment by slhck** [comment]
I'm not going to recommend you to mess around with your system more than you appear to already have 😉 — especially if you already disabled SIP and try to symlink some system binaries/frameworks. It may make sense to start with a fresh system.

**Comment by peterjumper** [comment]
Sorry for causing the trouble , i do find out there is a export problem:
export DYLD_LIBRARY_PATH="$(brew --prefix)/lib:$DYLD_LIBRARY_PATH"
