### ISSUE TITLE
Something funky going on? Cannot install, Error: invalid option

### ISSUE THREAD

**Issue by scottbert** [homebrew-ffmpeg/homebrew-ffmpeg#19]
When I run 
```
brew install homebrew-ffmpeg/ffmpeg/ffmpeg --with-decklink --with-fdk-aac --with-game-music-emu --with-libbluray --with-libbs2b --with-libcaca --with-libgsm --with-libmodplug --with-librsvg --with-libsoxr --with-libssh --with-libvidstab --with-libvmaf --with-libxml2 --with-opencore-amr --with-openh264 --with-openjpeg --with-openssl --with-rtmpdump --with-rubberband --with-speex --with-srt --with-tesseract --with-two-lame --with-wavpack --with-webp --with-xvid --with-zeromq --with-zimg
```
I get
`Error: invalid option: --with-decklink` and prints out brew’s options. If I remove `--with-decklink` it does the same with `—with-fdc-aac` etc. Did something change somewhere?

**Comment by retokromer** [comment]
If you use Blackmagic DeckLink, possibly the [formula](https://github.com/amiaopensource/homebrew-amiaos/blob/master/ffmpegdecklink.rb) provided by the AMIA Open Source team works better?

**Comment by retokromer** [comment]
Regarding the `--with-decklink` option: the DeckLink SDK has to be installed **before** running the FFmpeg formula. One possibility is to use:
```
brew install amiaopensource/amiaos/decklinksdk
```
See the [ReadMe](https://github.com/homebrew-ffmpeg/homebrew-ffmpeg#included-libraries).

**Comment by retokromer** [comment]
@scottbert Could you resolve it? I am sorry, I cannot reproduce the issue on my end.

**Comment by scottbert** [comment]
I just tried again and I can no longer reproduce it either! Thanks for the suggestions though :)
