### ISSUE TITLE
Support for libjack

### ISSUE THREAD

**Issue by slhck** [homebrew-ffmpeg/homebrew-ffmpeg#2]
See https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/pull/3

**Comment by retokromer** [comment]
What is the status of this one (it’s open since more than two years)

**Comment by slhck** [comment]
I forgot about tihs one. Didn't have Homebrew on my dev machine for a while, but now I updated the PR. It builds under Linux, and I'll test under macOS too.
