### ISSUE TITLE
[Error] dyld: Library not loaded: /usr/local/opt/x265/lib/libx265.179.dylib

### ISSUE THREAD

**Issue by onoakino** [homebrew-ffmpeg/homebrew-ffmpeg#20]
Hi! I'm getting an error with ffmpeg. My OS is MacOS Mojave. Any ffmpeg commands I enter on the terminal would throw this error:

musangs-MacBook-Pro:~ musang$ **ffmpeg --version
dyld: Library not loaded: /usr/local/opt/x265/lib/libx265.179.dylib
  Referenced from: /usr/local/bin/ffmpeg
  Reason: image not found
Abort trap: 6`**

When I try to upgrade:

`musangs-MacBook-Pro:~ musang$ brew upgrade --fetch-HEAD ffmpeg
Updating Homebrew...
Error: **Calling brew tap-pin user/tap is disabled! Use fully-scoped user/tap/formula naming instead.**

Here is my tap list:

musangs-MacBook-Pro:~ musang$ brew tap
adoptopenjdk/openjdk
homebrew-ffmpeg/ffmpeg
homebrew/bundle
homebrew/cask
homebrew/cask-fonts
homebrew/core
sidneys/homebrew

And here is where ffmpeg is located on my path:

musangs-MacBook-Pro:~ musang$ which ffmpeg
/usr/local/bin/ffmpeg

**Comment by retokromer** [comment]
Please try:
```
brew reinstall ffmpeg
```

**Comment by retokromer** [comment]
(Probably, you upgraded `x265` after having installed `ffmpeg`. Reinstalling should resolve the issue.)

**Comment by retokromer** [comment]
@onoakino Did reinstalling FFmpeg resolve the issue?

**Comment by slhck** [comment]
From my experience this happens from time to time with x264/x265 and ffmpeg via Homebrew. It's not related to this formula directly. See: https://github.com/Homebrew/homebrew-core/issues/33364

**Comment by retokromer** [comment]
Yep, that’s why I suggested to recompile.

**Comment by retokromer** [comment]
I presume, reinstalling resolves the issue, therefore closing this. If not, then please reopen.
