### ISSUE TITLE
version 4.2.1

### ISSUE THREAD

**Issue by retokromer** [homebrew-ffmpeg/homebrew-ffmpeg#4]
If we “ignore” the `mpv` issue, e.g. by adding a [caveat](https://github.com/AVpres/homebrew-formulae/blob/8b8e89db825e8e9d0e897a99fcffd305b8dd2464/ffmpeg.rb#L182-L192), then we could easily upgrade to 4.2.1 here. 

@slhck Any thoughts?

**Comment by slhck** [comment]
I'm fine with this option. People using this tap will most likely be willing to do these extra steps.

**Comment by retokromer** [comment]
Okay, I will open a PR later today. Thank you!
