### ISSUE TITLE
zsh: segmentation fault  ffmpeg

### ISSUE THREAD

**Issue by TheElectroclassics** [homebrew-ffmpeg/homebrew-ffmpeg#40]
I have a machine in the latest Catalina version that had 2 ffmpeg binaries, one from miniconda, and the other from homebrew. I removed miniconda completely and the homebrew one too. I instaled it using your tap but it's giving me segmentation fault error. I did the same thing on another laptop except this one only had the homebrew installation and it's working properly.

**Comment by retokromer** [comment]
I just have installed a few minutes on macOS 10.15 with all options enabled and it worked fine. Do you have more information?

**Comment by TheElectroclassics** [comment]
sadly no, I really don't know how to troubleshoot this, since, as I stated in my original comment, it did installed correctly on a second machine. The only difference was that conda wasn't installed. I want to believe that the conda installed ffmepg was the one with the simlink (is that was it's called?).

**Comment by slhck** [comment]
I don't think we will be able to help you without any details. Please provide the exact command you are running, and any command line output you are getting when it's showing the segmentation fault.

**Comment by TheElectroclassics** [comment]
Homebrew Config
`HOMEBREW_VERSION: 2.4.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: e9c7c26e0a0234a3ad6647d7bed76b82f3fa8125
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: af74615dae5a98a8210a6f75f877fe7defb08239
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.1cFCkHhlig/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 4
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.27.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 14.0.1
macOS: 10.15.5-x86_64
CLT: 11.0.33.8
Xcode: 11.5
XQuartz: 2.7.11 => /opt/X11`

brew doctor
`Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.


Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  pkg-config
  libtool
  vde
  libssh2
  libusb
  python@3.8

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc`

after typing `ffmpeg` and hitting enter
`zsh: segmentation fault  ffmpeg`

**Comment by retokromer** [comment]
The output of `brew doctor` gives you tasks to accomplish.

**Comment by TheElectroclassics** [comment]
still, segmentation fault

**Comment by TheElectroclassics** [comment]
ran every task requiered by brew doctor, removed ffmpeg and reinstalled with this tap, and I still get the same error

**Comment by slhck** [comment]
Just to check, what does `which -a ffmpeg` output?

Also, `echo $PATH` just for completeness.

I'd like to make sure that the ffmpeg you're attempting to run is the one installed via this formula.

**Comment by TheElectroclassics** [comment]
Solved.

Here's what I did:

Reinstalled Command Line Tools
Uninstalled ffmepg from this tap
Installed ffmepg from homebrew
Removed ffmpeg from homebrew
Reinstalled ffmpeg from this tap.
