### ISSUE TITLE
[ENHANCEMENT] Support for DASH demuxer

### ISSUE THREAD

**Issue by bbgdzxng1** [homebrew-ffmpeg/homebrew-ffmpeg#42]
Please could `--enable-demuxer=dash` be added to the build script?

Current ffmpeg/4.3-with-options_2 does not support dash as an input format to FFmpeg suite of tools..
```
$ ffmpeg -formats | grep -e "DASH Muxer"
  E dash            DASH Muxer
```

Expected result
```
$ ffmpeg -formats | grep -e "DASH Muxer"
 DE dash            DASH Muxer
```

#### Test case 1 - Play DASH stream generated by FFmpeg

```
$ ffmpeg -hide_banner -i "http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_30fps_normal.mp4" -t "120" -codec:v "libx264" -codec:a "aac" -f "dash" "./index.mpd"
$ ffmpeg -loglevel "level+debug" -i "./index.mpd"
```
#### Test case 2 - 3rd party DASH stream

```
$ ffplay -i "https://storage.googleapis.com/shaka-demo-assets/bbb-dark-truths/dash.mpd"
```

Relevant Stack Exchange: https://stackoverflow.com/questions/28848917/playing-mpeg-dash-streaming-with-ffmpeg

Thanks for all your hard work in maintaining these builds.

**Comment by slhck** [comment]
Done, thanks for the suggestion.
You should manually reinstall, and we will provide a revision to enable this in new installations.

**Comment by bbgdzxng1** [comment]
Very cool guys.  Thank-you so much for actively supporting such a great build mechanism.  You guys are awesome.
