### ISSUE TITLE
Broken brew install due to x265 not being available

### ISSUE THREAD

**Issue by chaos-git** [homebrew-ffmpeg/homebrew-ffmpeg#47]
`$ brew install ffmpeg` results in:

```
==> Downloading https://bitbucket.org/multicoreware/x265/downloads/x265_3.4.tar.gz

curl: (22) The requested URL returned error: 403 Forbidden
Error: Failed to download resource "x265"
Download failed: https://bitbucket.org/multicoreware/x265/downloads/x265_3.4.tar.gz
```

Looks like the repo is no longer available on bitbucket.

Mac 10.12.6

**Comment by retokromer** [comment]
@chaos-git This issue is related to the `x265` formula, not to this one. You should report there.

**Comment by retokromer** [comment]
The Bitbucket repository is no longer available (it seems since 2020-08-03). The regular Homebrew formula need to be updated. I don’t have the time to do it now. – cc @slhck ?

**Comment by retokromer** [comment]
Thank you, @chaos-git, for reporting! Should be resolved in a couple of hours.

**Comment by retokromer** [comment]
@chaos-git The upstream PR has been merged a few minutes ago. Now it should work well again.
