### ISSUE TITLE
ERROR: libmp3lame >= 3.98.3 not found

### ISSUE THREAD

**Issue by ZGilbert** [homebrew-ffmpeg/homebrew-ffmpeg#51]
hello,  
when I use " brew upgrade homebrew-ffmpeg/ffmpeg/ffmpeg " , I get an error "ERROR: libmp3lame >= 3.98.3 not found"..

**Comment by retokromer** [comment]
Do you have more information? Please post the command you tried and the result you got. On which system are you working?

**Comment by retokromer** [comment]
@ZGilbert Could you possibly give any additional information? I cannot reproduce.

**Comment by retokromer** [comment]
I cannot reproduce and I am closing. Feel free to reopen if there is more information.
