### ISSUE TITLE
Missing --with-libass support

### ISSUE THREAD

**Issue by mcandre** [homebrew-ffmpeg/homebrew-ffmpeg#56]

**Comment by retokromer** [comment]
`libass` is enabled by default.

**Comment by retokromer** [comment]
@slhck Should I make it optional or modify the documentation?

**Comment by slhck** [comment]
I think we should leave everything as is. It's documented and changing the defaults is not so nice.

**Comment by retokromer** [comment]
I fully agree with you, @slhck
