### ISSUE TITLE
The libavformat patch no longer applies successfully

### ISSUE THREAD

**Issue by mockjv** [homebrew-ffmpeg/homebrew-ffmpeg#58]
Here's what I get when running a re-install:

```shell
❯ brew reinstall /Users/mock/Desktop/ffmpeg.rb
==> Downloading https://github.com/FFmpeg/FFmpeg/commit/7c59e1b0f285cd7c7b35fcd71f49c5fd52cf9315.patch?full_index=1
Already downloaded: /Users/mock/Library/Caches/Homebrew/downloads/c585557298843eab846c569ff84eb7623db209cd15cfd74b2d736a1e7d86a55c--7c59e1b0f285cd7c7b35fcd71f49c5fd52cf9315.patch
==> Cloning https://github.com/FFmpeg/FFmpeg.git
Updating /Users/mock/Library/Caches/Homebrew/ffmpeg--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at e5be4c5 avcodec/hevcdec: constrained intra predict, do not check top left IS_INTRA if it's not available
==> Reinstalling ffmpeg --with-fdk-aac
==> Patching
==> Applying 7c59e1b0f285cd7c7b35fcd71f49c5fd52cf9315.patch
patching file libavformat/libsrt.c
Hunk #1 FAILED at 313.
Hunk #2 FAILED at 337.
2 out of 2 hunks FAILED -- saving rejects to file libavformat/libsrt.c.rej
```

**Comment by retokromer** [comment]
@mockjv Thank you for reporting! You did try to install the HEAD, not the version 4.3.1, right?

**Comment by retokromer** [comment]
Thank you! Yes, that was my question. Sorry for being unclear.

The build seems still to work. If I am not wrong, it’s not a big deal: just apply the patch for the build, but not for the HEAD (because it has already been merged). Let me check…

**Comment by exekutive** [comment]
I am getting the same message as mockjv and the build does NOT complete.

**Comment by exekutive** [comment]
removed option '--HEAD" and build finished, but ffmpeg doesn't work:

dyld: Library not loaded: @rpath/libclang_rt.ubsan_osx_dynamic.dylib
  Referenced from: /usr/local/opt/game-music-emu/lib/libgme.0.dylib
  Reason: image not found
zsh: abort      ffmpeg

**Comment by exekutive** [comment]
reinstalled without '--with-game-music-emu' option and it seems to work fine

**Comment by retokromer** [comment]
@mockjv Now both the last release and the head should work again.

**Comment by exekutive** [comment]
now I'm getting 
`Unknown option "--enable-libwavpack".
`

**Comment by retokromer** [comment]
Unless I am missing something, this is not be related with the libavformat patch?

**Comment by mockjv** [comment]
@retokromer Looks like my installs are going through fine now.  Thanks!
