### ISSUE TITLE
Failure To Build Regardless Whether --HEAD and/or --COMPACT Are USED

### ISSUE THREAD

**Issue by Rogue-Git-Dev** [homebrew-ffmpeg/homebrew-ffmpeg#63]
This fork of FFMPEG fails to build on my system regardless whether I use —HEAD, --COMPACT, or neither. My system is running Mac OS Big Sur beta version 11.1 build 20C5061b. All of the dependencies listed on the main GitHub page for this tap are installed. The following are different outputs based on the combinations of arguments. Note each output produces an error pertinent to the dependencies installed already.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
➜ brew install homebrew-ffmpeg/ffmpeg/ffmpeg $(brew options homebrew-ffmpeg/ffmpeg/ffmpeg --compact) --HEAD
==> Installing ffmpeg from homebrew-ffmpeg/ffmpeg
==> Cloning https://github.com/FFmpeg/FFmpeg.git
Updating /Users/User/Library/Caches/Homebrew/ffmpeg--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 0dac317 avformat/framecrcenc: Make side-data checksums endian-independent
==> ./configure --prefix=/usr/local/Cellar/ffmpeg/HEAD-0dac317_6 --enable-shared --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libaom --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-libsnappy --enable-lib
Last 15 lines from /Users/User/Library/Logs/Homebrew/ffmpeg/01.configure:
--enable-libxml2
--enable-libxvid
--enable-libzimg
--enable-libzmq
--enable-openssl
--enable-nonfree
--enable-decklink
--extra-cflags=-I/usr/local/include
--extra-ldflags=-L/usr/local/include
--enable-version3
--enable-libopencore-amrnb
--enable-libopencore-amrwb

Unknown option "--enable-libwavpack".
See ./configure --help for available options.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
➜ brew install homebrew-ffmpeg/ffmpeg/ffmpeg $(brew options homebrew-ffmpeg/ffmpeg/ffmpeg --compact)       
==> Installing ffmpeg from homebrew-ffmpeg/ffmpeg
==> Downloading https://github.com/FFmpeg/FFmpeg/commit/7c59e1b0f285cd7c7b35fcd71f49c5fd52cf9315.patch?full_index=1
Already downloaded: /Users/User/Library/Caches/Homebrew/downloads/c585557298843eab846c569ff84eb7623db209cd15cfd74b2d736a1e7d86a55c--7c59e1b0f285cd7c7b35fcd71f49c5fd52cf9315.patch
==> Downloading https://ffmpeg.org/releases/ffmpeg-4.3.1.tar.xz
Already downloaded: /Users/User/Library/Caches/Homebrew/downloads/907d44c10ce0824ba8d0acb013a260cf4114a463a371b204afae8e3588f76792--ffmpeg-4.3.1.tar.xz
==> Patching
==> Applying 7c59e1b0f285cd7c7b35fcd71f49c5fd52cf9315.patch
patching file libavformat/libsrt.c
==> ./configure --prefix=/usr/local/Cellar/ffmpeg/4.3.1-with-options_6 --enable-shared --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libaom --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-libsnappy --enab
Last 15 lines from /Users/User/Library/Logs/Homebrew/ffmpeg/01.configure:
--enable-nonfree
--enable-decklink
--extra-cflags=-I/usr/local/include
--extra-ldflags=-L/usr/local/include
--enable-version3
--enable-libopencore-amrnb
--enable-libopencore-amrwb

ERROR: libbluray not found using pkg-config

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
➜ brew install homebrew-ffmpeg/ffmpeg/ffmpeg --HEAD 
==> Installing ffmpeg from homebrew-ffmpeg/ffmpeg
==> Cloning https://github.com/FFmpeg/FFmpeg.git
Updating /Users/User/Library/Caches/Homebrew/ffmpeg--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 0dac317 avformat/framecrcenc: Make side-data checksums endian-independent
==> ./configure --prefix=/usr/local/Cellar/ffmpeg/HEAD-0dac317_6 --enable-shared --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libaom --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-libsnappy --enable-lib
Last 15 lines from /Users/User/Library/Logs/Homebrew/ffmpeg/01.configure:
--enable-libass
--enable-demuxer=dash
--disable-libjack
--disable-indev=jack
--enable-opencl
--enable-videotoolbox
--disable-htmlpages

ERROR: fontconfig not found using pkg-config

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.

**Comment by scribblemaniac** [comment]
> ➜ brew install homebrew-ffmpeg/ffmpeg/ffmpeg $(brew options homebrew-ffmpeg/ffmpeg/ffmpeg --compact) --HEAD
...
Unknown option "--enable-libwavpack".

ffmpeg is dropping support for libwavpack, so remove the --with-wavpack flag.

> ➜ brew install homebrew-ffmpeg/ffmpeg/ffmpeg $(brew options homebrew-ffmpeg/ffmpeg/ffmpeg --compact)
..
ERROR: libbluray not found using pkg-config

Libbluray is not installed, or it's not in a place where ffmpeg can find it. This should be installed automatically as a dependency for the formula.

> ➜ brew install homebrew-ffmpeg/ffmpeg/ffmpeg --HEAD
...
ERROR: fontconfig not found using pkg-config

Again you are missing a dependency, this time fontconfig.

To fix the last two issues, try running the same command but with `--dependencies-only` added first, and make sure everything installs successfully, then run the command as you have it now. Other things to try: check `brew doctor` or `brew reinstall` any dependencies which are causing the install to fail.

**Comment by Rogue-Git-Dev** [comment]
I knew not WAVPack support was to be removed. It is included in all options which made me believe otherwise. How can I instal using all options precluding WAVPack? WAVPack is installed. If I remove it, will that be the solution?

Both libbluray and fontconfig are installed; that has not changed. PKG-Config has no non-standard prefixes in my path or any modifications to its configuration. These PKG-Config related error messages arose since I upgraded my machine to Big Sur although that may not be the culprit.

**Comment by scribblemaniac** [comment]
Wavpack is in all options because it is supported by the latest stable build of ffmpeg. It's not reasonable to support the unstable head since it changes so often. You can run `brew options homebrew-ffmpeg/ffmpeg/ffmpeg --compact` remove the flag you don't want, and copy it into you command, replacing `$(brew options homebrew-ffmpeg/ffmpeg/ffmpeg --compact)`.

**Comment by Rogue-Git-Dev** [comment]
Apologies but I fail to understand what you mean by replacing part of that command with remove and whichever dependency. I may need an example.

Do you recommend not to use HEAD builds of any dependency for FFMPEG, every dependency for FFMPEG, or only certain dependencies? If the latter, which ones?

**Comment by scribblemaniac** [comment]
`brew install homebrew-ffmpeg/ffmpeg/ffmpeg --with-chromaprint --with-decklink --with-fdk-aac --with-game-music-emu --with-libbluray --with-libbs2b --with-libcaca --with-libgsm --with-libmodplug --with-librsvg --with-libsoxr --with-libssh --with-libvidstab --with-libvmaf --with-libxml2 --with-opencore-amr --with-openh264 --with-openjpeg --with-openssl --with-openssl@1.1 --with-rav1e --with-rtmpdump --with-rubberband --with-speex --with-srt --with-tesseract --with-two-lame --with-webp --with-xvid --with-zeromq --with-zimg --HEAD`

I would not recommend you install anything with HEAD unless you have a good reason to (for example some feature you want or fix for an issue you are having that is not in the latest stable version).

**Comment by Rogue-Git-Dev** [comment]
Now I understand: replace the command with the individual flags of each of the dependencies. I tried to avoid that so thanks for making that easy to copy and paste. Is it feasible to implement a —without-[dependency] flag, or is this out of the scope of FFMPEG or any formula in general?

**Comment by Rogue-Git-Dev** [comment]
The same libbluray related error arose when using the exact line you wrote. Why do you think PKG-Config all of a sudden cannot find libbluray? I uninstalled PKG-Config, reinstalled PKG-Config, uninstalled libbluray, and reinstalled libbluray all to no avail. I will not be surprised if fontconfig is the next one to cause problems. Both of these are linked via Homebrew so that is not the problem.

**Comment by Rogue-Git-Dev** [comment]
I never will understand why, but today the build was successful. No errors occurred; however, I changed nothing since I opened this issue. PKG-Config decided to find libbluray and fontconfig.

**Comment by retokromer** [comment]
On my end, it works fine on macOS `11.0.1`, but I’ll not try to reproduce on `11.1 beta 2` now (because I rarely have the time to run after beta releases ;-)

**Comment by retokromer** [comment]
>I never will understand why, but today the build was successful. No errors occurred; however, I changed nothing since I opened this issue. PKG-Config decided to find libbluray and fontconfig.

The HEAD is evolving constantly…

In my opinion, it’s simpler to use releases for actual work, unless you need a feature that is not yet in a the last release, but only on the development branch.

>Is it feasible to implement a --without-[dependency] flag, or is this out of the scope of FFMPEG or any formula in general?

That should be possible, yet what’s the benefit?

The current formula can already be parameterized according to any needs. Your approach would include the new libraries and you would have to exclude them each time a new one is added, if not needed.

**Comment by Rogue-Git-Dev** [comment]
The benefit of the --without-[dependency] argument would be avoiding to type all of the flags. One could type the same command for --COMPACT and append --without-[dependency] to avoid removing --compact and using the individual flags.

**Comment by slhck** [comment]
Please note that not everyone wants to always install all the options.

In particular, some options in this tap are only meaningful if you have other third-party SDKs installed (e.g., the DeckLink SDK) – or they are only useful for a very small number of people (e.g., snappy).

This is why we provide some defaults like libx264 but not others.

**Comment by Rogue-Git-Dev** [comment]
Of course; that is understandable. I am considering the edge case wherein a dependency [stable or HEAD] fails to be recognised although it is installed. PKG-Config has no HEAD but it failed to recognise both libbluray and fontconfig on my machine although both were stable builds installed at those junctures. This would be a quick way to instal all dependencies without certain ones provided the edge case exists and not type all of the individual dependency flags. My suggestion is for convenience really and not of particular importance.

**Comment by slhck** [comment]
Sure. Unfortunately we cannot provide both modes of operation. Either we have some default formulae that are sensible and additional ones with `--with-XXX`, or we have all dependencies by default and a `--without` mechanism. If both should exist at the same time, Homebrew itself would have to provide such a mechanism.

**Comment by Rogue-Git-Dev** [comment]
I knew that not. Thanks for the explanation.

**Comment by slhck** [comment]
By the way, at least for me, the "not found using pkg-config" errors from ffmpeg are often red herrings. I frequently get those printed at the end of a configuration/compilation process when it errors out, but the *actual* error is often logged much earlier and to be found in the ffmpeg compilation log itself. It should be in some temporary folder that Homebrew creates.

Anyway, good that it worked for you now.

**Comment by Rogue-Git-Dev** [comment]
Do you know where this log resides on Mac OS? Perhaps I can retrieve it before it is deleted provided this occurs in future.

**Comment by retokromer** [comment]
>Do you know where this log resides on Mac OS? Perhaps I can retrieve it before it is deleted provided this occurs in future.

At `~/Library/Logs/Homebrew/` if I remember carefully.
