### ISSUE TITLE
Another Error In Make Step

### ISSUE THREAD

**Issue by Rogue-Git-Dev** [homebrew-ffmpeg/homebrew-ffmpeg#64]
Homebrew encountered two errors whilst attempting to reinstall FFMPEG. After it updated a couple of dependencies of FFMPEG it tried to reinstall FFMPEG because it called it broken. The following is the output of that process. I cannot begin to decipher the make errors to know what is the problem.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
brew reinstall ffmpeg
==> Cloning https://github.com/FFmpeg/FFmpeg.git
Updating /Users/User/Library/Caches/Homebrew/ffmpeg--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 6c24f2b avformat/rtpdec: export Opus extradata in ff_rtp_parse_open()
==> Reinstalling homebrew-ffmpeg/ffmpeg/ffmpeg --with-chromaprint --with-decklink --with-fdk-aac --with-game-music-emu --with-librsvg --with-libsoxr --with-libssh --with-tesseract --with-libvidstab --with-opencore-amr --with-openh264 --wi
==> ./configure --prefix=/usr/local/Cellar/ffmpeg/HEAD-6c24f2b_6 --enable-shared --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libaom --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-libsnappy --enable-lib
==> make install
Last 15 lines from /Users/User/Library/Logs/Homebrew/ffmpeg/02.make:
make: *** Waiting for unfinished jobs....
 error: use of undeclared identifier 'kCFStringEncodingUTF8'
    CFStringGetCString(w, s, 255, kCFStringEncodingUTF8);
                                  ^
2 errors generated.
make: *** [libavdevice/decklink_enc.o] Error 1
In file included from libavdevice/decklink_dec.cpp:54:
libavdevice/decklink_common.h:58:35: error: unknown type name 'CFStringRef'
static char *dup_cfstring_to_utf8(CFStringRef w)
                                  ^
libavdevice/decklink_common.h:61:35: error: use of undeclared identifier 'kCFStringEncodingUTF8'
    CFStringGetCString(w, s, 255, kCFStringEncodingUTF8);
                                  ^
2 errors generated.
make: *** [libavdevice/decklink_dec.o] Error 1

**Comment by slhck** [comment]
To me this seems like an upstream error in ffmpeg itself. Since you're building the HEAD version, any upstream bugs might show during Homebrew installation.

Can you please try uninstalling ffmpeg completely and reinstalling it without the HEAD opption?

**Comment by Rogue-Git-Dev** [comment]
That failed. The output seems to be almost identical.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
- ➜ brew install homebrew-ffmpeg/ffmpeg/ffmpeg $(brew options homebrew-ffmpeg/ffmpeg/ffmpeg --compact)
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 3 taps (homebrew/cask-versions, homebrew/core and homebrew/cask).
==> Updated Formulae
Updated 2 formulae.
==> Updated Casks
Updated 5 casks.

==> Installing ffmpeg from homebrew-ffmpeg/ffmpeg
==> Downloading https://homebrew.bintray.com/bottles/wavpack-5.3.0.big_sur.bottle.1.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/78570562d7429a48decbdd52fad54a20f8c768d8a529c314e424a60ede55ecb9?response-content-disposition=attachment%3Bfilename%3D%22wavpack-5.3.0.big_sur.bottle.1.tar.gz%22&Policy=eyJTdGF0ZW
######################################################################## 100.0%
==> Downloading https://github.com/FFmpeg/FFmpeg/commit/7c59e1b0f285cd7c7b35fcd71f49c5fd52cf9315.patch?full_index=1
######################################################################## 100.0%
==> Downloading https://ffmpeg.org/releases/ffmpeg-4.3.1.tar.xz
######################################################################## 100.0%
==> Installing dependencies for homebrew-ffmpeg/ffmpeg/ffmpeg: wavpack
==> Installing homebrew-ffmpeg/ffmpeg/ffmpeg dependency: wavpack
==> Pouring wavpack-5.3.0.big_sur.bottle.1.tar.gz
/usr/local/Cellar/wavpack/5.3.0: 20 files, 835.5KB
==> Installing homebrew-ffmpeg/ffmpeg/ffmpeg --with-chromaprint --with-decklink --with-fdk-aac --with-game-music-emu --with-librsvg --with-libsoxr --with-libssh --with-tesseract --with-libvidstab --with-opencore-amr --with-openh264 --with
==> Patching
==> Applying 7c59e1b0f285cd7c7b35fcd71f49c5fd52cf9315.patch
patching file libavformat/libsrt.c
==> ./configure --prefix=/usr/local/Cellar/ffmpeg/4.3.1-with-options_6 --enable-shared --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libaom --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-libsnappy --enab
==> make install
Last 15 lines from /Users/User/Library/Logs/Homebrew/ffmpeg/02.make:
                                  ^
3 errors generated.
CC	libavfilter/af_acrusher.o
make: *** [libavdevice/decklink_common.o] Error 1
make: *** Waiting for unfinished jobs....
2 errors generated.
libavdevice/decklink_dec.cpp:771:21: error: unknown type name '__CFString'
                    DECKLINK_STR decklink_tc;
                    ^
libavdevice/decklink_common.h:64:31: note: expanded from macro 'DECKLINK_STR'
#define DECKLINK_STR    const __CFString *
                              ^
make: *** [libavdevice/decklink_enc.o] Error 1
3 errors generated.
make: *** [libavdevice/decklink_dec.o] Error 1

**Comment by slhck** [comment]
In this case it seems to me that the DeckLink SDK itself is causing the problem. Have you recently changed anything related to that?

(I haven't used that SDK yet but I assume there are some version constraints in terms of what ffmpeg works with.)

**Comment by Rogue-Git-Dev** [comment]
It might be the version installed currently. If not already, should I instal the stable version?

**Comment by slhck** [comment]
Yes. I wouldn't be surprised if ffmpeg didn't work with unstable third party SDKs.

**Comment by Rogue-Git-Dev** [comment]
Considering its perceived instability, do you think it is wise to remove support for it?

**Comment by slhck** [comment]
I don't know how DeckLink SDK and ffmpeg interact; ffmpeg does not seem to require a specific version of DeckLink SDK, but I also don't know which version of the latter you have installed. In general, no, support for it shouldn't be removed.

Looking more closely though, the error stems from the compiler not knowing what  `__CFString` is, which is a bit surprising since it [should be available](https://github.com/opensource-apple/CF/blob/master/CFString.c) under macOS.

Since that part of the FFmpeg code has been there for 3 years unchanged, I guess the error is with the configuration of your compiler.

**Comment by Rogue-Git-Dev** [comment]
It was not the latest stable version installed but it is now and that fixed installation of FFMPEG. The brew configuration is as follows. Is FFMPEG optimised for my system as a HEAD build? I presume HEAD builds optimise for each individual’s system [CPU et cetera] thus the answer would be yes.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
brew config
HOMEBREW_VERSION: 2.7.1-119-g4a90a5a
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4a90a5a5d6210b3ab526d68c3c9330c91bc4a55d
Last commit: 34 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 39af1529f356db9c9b20409e24ed763d8950f960
Core tap last commit: 6 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_AUTO_UPDATE_SECS: 1
HOMEBREW_CASK_OPTS: []
HOMEBREW_CLEANUP_MAX_AGE_DAYS: 1
HOMEBREW_CURLRC: set
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.9mPh1htKp3/org.macosforge.xquartz:0
HOMEBREW_DISPLAY_INSTALL_TIMES: set
HOMEBREW_EDITOR: /usr/local/bin/mate --name 'Git Commit Message' -w -l 1
HOMEBREW_FORCE_BREWED_CURL: set
HOMEBREW_FORCE_BREWED_GIT: set
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 12
HOMEBREW_NO_COLOR: set
HOMEBREW_NO_EMOJI: set
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.30.0 => /usr/local/opt/git/bin/git
Curl: 7.74.0 => /usr/local/opt/curl/bin/curl
Java: 16, 15.0.1, 13.0.1
macOS: 11.2-x86_64
CLT: 12.3.0.0.1.1607026830
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11

**Comment by slhck** [comment]
> Is FFMPEG optimised for my system as a HEAD build? I presume HEAD builds optimise for each individual’s system [CPU et cetera] thus the answer would be yes

No, that's not what HEAD builds do. HEAD simply means: Get the ultra-latest version of ffmpeg's Git repository. These are usually not stable in the sense that they might not work with certain third-party libraries, or have changes to the build system itself. That's why we bundle a fixed version (4.3.1 at this point). So unless you know you need them, don't use HEAD builds.

**Comment by retokromer** [comment]
>macOS: 11.2-x86_64

To my knowledge this is still in beta.

FYI: last week I’ve installed successfully FFmpeg 4.3.1 and DeckLink SDK on macOS 11.1.

**Comment by slhck** [comment]
Ah, I didn't spot that. It may very well be that they're changing some internals there.

**Comment by Rogue-Git-Dev** [comment]
Yes, I used pre-release builds of Mac OS since 2014 as well as iOS since 2014 and tvOS for as much time as it existed for public beta users. I know what I am doing with that and Homebrew has not presented problems attributable to pre-release of Mac OS.

**Comment by retokromer** [comment]
As said, last week I setup U-matic digitisation stations using the current DeckLink SDK and vrecord on macOS 11.1, and it has worked just fine all today.

**Comment by retokromer** [comment]
@Rogue-Git-Dev Do you still experience this error?

**Comment by Rogue-Git-Dev** [comment]
No. I believe it was attributable to Snappy, but it was months back and I cannot remember exactly.
