### ISSUE TITLE
libavresample >=3.0.0

### ISSUE THREAD

**Issue by Vaoske** [homebrew-ffmpeg/homebrew-ffmpeg#68]
Thanks for your work!

I need the pkg libavresample (>=3.0.0), is it possible to compile with your script?

Greets from The Netherlands
Vaoske

**Comment by slhck** [comment]
libavresample is deprecated and should not be used. You can use swresample instead: https://ffmpeg.org/libswresample.html

**Comment by retokromer** [comment]
>is it possible to compile with your script?

Currently no, sorry.

If I remember carefully, `libavresample` is a deprecated alternative to the native `libswresample`. It is not enabled by default. If you really need it, then you should compile it by adding the `--enable-avresample` configure option.

Best regards from freezing Switzerland

**Comment by retokromer** [comment]
Oh, @slhck was quicker!

**Comment by slhck** [comment]
You can also follow one of the compilation guides here: https://trac.ffmpeg.org/wiki/CompilationGuide

Then use the additional configure option as suggested above!
