### ISSUE TITLE
Error fetching Tap

### ISSUE THREAD

**Issue by jennifert** [homebrew-ffmpeg/homebrew-ffmpeg#74]
## Bug Reports

- [x] I ran `brew update` and can still reproduce the problem
- [x] I ran `brew doctor`, fixed all issues and can still reproduce the problem
- [x] I ran `brew config` and `brew doctor` and included their output with my issue
- [x] I verified that this is an issue with *this* tap and not any other `ffmpeg` version

## Expected behavior

Tap is reachable when running brew update command (with no errors).

## Actual behavior

When running update command, there is an error fetching the tap (failed to reach). Have had ffmpeg installed and updating since June and had no issues installed (have the latest X-code tools).

## Command

The exact command you were trying to run:

```
brew update
```

The output that you got:

```
Error: Fetching /usr/local/Homebrew/Library/Taps/homebrew-ffmpeg/homebrew-ffmpeg failed!
```
## Output of `brew config` and `brew doctor` commands

`brew config`:

```
HOMEBREW_VERSION: 3.0.7
ORIGIN: https://github.com/Homebrew/brew
HEAD: 59ada80ca740e72d29e625079395ee91cae4b3cf
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 77345310f03b0dd8c6f16b79d50b9c49dc0e7e5f
Core tap last commit: 6 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.31.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.3-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A
```

`brew doctor`:

```
Your system is ready to brew.
```

**Comment by harrygallagher4** [comment]
I had the same error. It looks like the repo just changed the default branch to `main` instead of `master`. I'm not a git expert, but managed to fix it by manually checking out `main` locally and changing `HEAD`. 

(some of these commands may be unnecessary)
```sh
cd /usr/local/Homebrew/Library/Taps/homebrew-ffmpeg/homebrew-ffmpeg
git fetch
git checkout main
git remote prune origin
git branch -D master
```

Then replacing "master" with "main" in `.git/refs/remotes/origin/HEAD` which is probably not the best idea, but it worked.

**Comment by slhck** [comment]
Thanks for reporting this issue. I'm surprised that they'd do this to existing repos. This is bound to break much more stuff.

I'm inclined to rename it back to master just to prevent further issues. But then again this should be fixed in brew itself, no?

**Comment by slhck** [comment]
A workaround is suggested [here](https://github.com/Homebrew/brew/issues/10766#issuecomment-803263988):

```
brew untap -f homebrew-ffmpeg/ffmpeg
brew tap homebrew-ffmpeg/ffmpeg
```

**Comment by slhck** [comment]
As a quick fix, I've renamed `main` back to `master`. I do not want to force our users to manually fix something that `brew` apparently cannot handle yet.

If this issue persists please reopen.

**Comment by retokromer** [comment]
@slhck `master` is considered a [racist](https://sfconservancy.org/news/2020/jun/23/gitbranchname/) term. I guess the recommended fix is:
```
git branch -m master main
git fetch origin
git branch -u origin/main main
```

**Comment by slhck** [comment]
I am aware of the possible/recommended fix, but that seems like a complicated workaround.

I would like to avoid going into the discussion behind the naming of the branch; that ship has sailed and there are [other opinions, too](https://mooseyanon.medium.com/github-f-ck-your-name-change-de599033bbbe). My personal opinion does not matter and should not matter (white cis-male speaking here), but what I can observe is that this action will lead to unforeseen behavior that will ultimately confuse end users.

I have no issue with going forward with a different default name (like for `git` or new GitHub projects), but switching the branch on existing projects is – as demonstrated by this issue – not a good solution.

Let's wait until `brew` or `git` can handle this transparently, then we can of course rename the branch.

**Comment by retokromer** [comment]
>I am aware of the possible/recommended fix, but that seems like a complicated workaround.

Indeed! I fully agree with you.

**Comment by jennifert** [comment]
Ah, i see. Thank you for explaining! Its working now, though I should have tried the untap, I was thinking of it, but then was not sure. Thank you all for the help! :)

**Comment by slhck** [comment]
@retokromer Just to make sure, did you change the branch name or was it done automatically?

**Comment by sjackman** [comment]
> `brew tap --repair` should fix that, and `brew update` should detect the rename and instruct a user to run `brew tap --repair`.

See https://github.com/Homebrew/brew/issues/10424#issuecomment-803637827
