### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by scottbert** [homebrew-ffmpeg/homebrew-ffmpeg#8]
On Catalina with the most up to date homebrew and this version of ffmpeg - it was working earlier today, but then I updated homebrew which updated the following:

```
vim 8.1.2100 -> 8.1.2150
libheif 1.5.1 -> 1.5.1_1
node@8 8.16.1 -> 8.16.2
exiftool 11.59 -> 11.70
gdk-pixbuf 2.38.2 -> 2.40.0
yarn 1.19.0 -> 1.19.1
librsvg 2.46.1 -> 2.46.2
mysql 8.0.17_1 -> 8.0.18
youtube-dl 2019.09.28 -> 2019.10.16
x264 r2917 -> r2917_1
x265 3.1.2 -> 3.2
node 12.11.1 -> 12.12.0
```
Now when I try and run ffmpeg I get `Segmentation fault: 11`

Anything I can do to give you more information, shout? I'm suspecting libheif, x264 or x265 to be the culprit but I am not a developer and I don't know :)

**Comment by retokromer** [comment]
Should be resolved in https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/pull/7

**Comment by retokromer** [comment]
@scottbert Could you possibly try again to install and report back? Thank you!

**Comment by scottbert** [comment]
Should I uninstall and reinstall or merely update?

**Comment by scottbert** [comment]
Seems to work, thanks!

**Comment by retokromer** [comment]
Excellent, thanks for reporting.
