### ISSUE TITLE
Error when installing ffmpeg with libvmaf

### ISSUE THREAD

**Issue by marcelgeibel** [homebrew-ffmpeg/homebrew-ffmpeg#82]
Hi, 
wanting to install ffmpeg with the libvamf option as described here: https://github.com/homebrew-ffmpeg/homebrew-ffmpeg, I encountered following error in the build process:

marcelgeibel@Marcels-MBP-2 ~ % brew install homebrew-ffmpeg/ffmpeg/ffmpeg --with-libvmaf
==> Installing ffmpeg from homebrew-ffmpeg/ffmpeg
==> Downloading https://ffmpeg.org/releases/ffmpeg-4.4.tar.xz
Already downloaded: /Users/marcelgeibel/Library/Caches/Homebrew/downloads/837c094bbbd62f9664825da5b8206acd9a27ed63510f91410034a4a1572d3750--ffmpeg-4.4.tar.xz
==> ./configure --prefix=/usr/local/Cellar/ffmpeg/4.4-with-options --enable-shar
==> make install
Last 15 lines from /Users/marcelgeibel/Library/Logs/Homebrew/ffmpeg/02.make:
INSTALL	libavfilter/version.h
GEN	libavfilter/libavfilter.pc
./ffbuild/pkgconfig_generate.sh: line 21: libswscale/libswscale.version: Interrupted system call
make: *** [libavdevice/libavdevice.pc] Error 1
make: *** Waiting for unfinished jobs....
INSTALL	libavformat/avformat.h
INSTALL	libavformat/avio.h
INSTALL	libavformat/version.h
STRIP	libswresample/x86/audio_convert.o
STRIP	libavcodec/x86/vp9lpf_16bpp.o
STRIP	libavcodec/x86/simple_idct.o
STRIP	libavcodec/x86/vp9itxfm_16bpp.o
STRIP	libavcodec/x86/hevc_mc.o
STRIP	libavcodec/x86/vp9lpf.o
STRIP	libavcodec/x86/vp9itxfm.o

Is there a fix to this error? Thanks!

**Comment by retokromer** [comment]
Please provide [the requested information](https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/issues/new?assignees=&labels=&template=bug_report.md). Thank!

**Comment by marcelgeibel** [comment]
I posted a new issue providing the information. Thank you!

**Comment by slhck** [comment]
Closed in favor of https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/issues/83
