### ISSUE TITLE
Add NEON patch to increase x265 encoding speed on ARM Apple Silicon

### ISSUE THREAD

**Issue by vbastianpc** [homebrew-ffmpeg/homebrew-ffmpeg#86]
## Is your feature request related to a problem? Please describe.

It is not a problem in itself, it is only an improvement.
I have compared ffmpeg builds encoding x265 with and without NEON on Apple M1. The speed increase is amazing: x3 with NEON patch.

## Describe the solution you'd like

Be able to compile ffmpeg with the NEON patch, like
`brew install homebrew-ffmpeg/ffmpeg/ffmpeg --with-neon`

[This guide](http://osxexperts.net) compiles ffmpeg with the NEON patch. Seems to be adding a simple `./configure --enable-neon`

**Comment by scribblemaniac** [comment]
Looks to me like all the changes for neon support are on the libx265 side, not ffmpeg, which would mean you would want to change the libx265 homebrew formula, not this one.

**Comment by slhck** [comment]
It does look like an ffmpeg configuration flag.

However, it requires patching ffmpeg, and we're a little reluctant to add things that are not part of the official FFmpeg code base, as it may break things for others and make upgrading complicated or even impossible if the patch doesn't get updated.

The page you linked to just offers the download itself. Could you please give us more info on where that patch is coming from?

**Comment by renaudguerin** [comment]
Interested in this as well. Apparently the patch has been submitted by Apple to the Handbrake project. [This thread has more info](
https://www.reddit.com/r/ffmpeg/comments/n21ukg/cant_compile_x265_for_arm64_apple_silicon_with/gwh2ohh/).

**Comment by renaudguerin** [comment]
[Even more info here](https://github.com/Vargol/ffmpeg-apple-arm64-build)

**Comment by robd003** [comment]
Here's a build optimized for the Apple M1 chips: https://github.com/Vargol/ffmpeg-apple-arm64-build

**Comment by mbirth** [comment]
Here you can download an ARM build containing the NEON patch: http://www.osxexperts.net

**Comment by silentj** [comment]
For folks looking for an easy (and trusted) way to get x265/ffmpeg with the NEON patch:

[The patch was made to x265 back in September 2021](https://bitbucket.org/multicoreware/x265_git/commits/4bf31dc15fb6d1f93d12ecf21fad5e695f0db5c0) but there hasn't been a new release containing it. Brew's `install --HEAD` command can build/install the `master` branch, but `master` isn't currently compiling under brew. So here's how you can hack brew to install a slightly older commit that both compiles and includes the NEON patch:

1. `brew uninstall --ignore-dependencies --force x265`
2. Edit `/opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/x265.rb`
3. Replace the `head` line with one that references a good commit:
```
head "https://bitbucket.org/multicoreware/x265_git.git", revision: "0b75c44c10e605fe9e9ebed58f04a46271131827"
```
4. `brew install --HEAD x265`

That should install a `HEAD-0b75c44` version of `x265` and re-install `ffmpeg` (and any other tools that are dependent on `x265`).

**Comment by sassa4ras** [comment]
> For folks looking for an easy (and trusted) way to get x265/ffmpeg with the NEON patch:
> 
> [The patch was made to x265 back in September 2021](https://bitbucket.org/multicoreware/x265_git/commits/4bf31dc15fb6d1f93d12ecf21fad5e695f0db5c0) but there hasn't been a new release containing it. Brew's `install --HEAD` command can build/install the `master` branch, but `master` isn't currently compiling under brew. So here's how you can hack brew to install a slightly older commit that both compiles and includes the NEON patch:
> 
> 1. `brew uninstall --ignore-dependencies --force x265`
> 2. Edit `/opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/x265.rb`
> 3. Replace the `head` line with one that references a good commit:
> 
> ```
> head "https://bitbucket.org/multicoreware/x265_git.git", revision: "0b75c44c10e605fe9e9ebed58f04a46271131827"
> ```
> 
>  4. `brew install --HEAD x265`
> 
> That should install a `HEAD-0b75c44` version of `x265` and re-install `ffmpeg` (and any other tools that are dependent on `x265`).

This is great, but now ffmpeg fails to run because it's linking to a different version of x265 dynamic library. I guess I'm dumb, but how would I get ffmpeg to recompile correctly with this patch?

**Comment by robd003** [comment]
> This is great, but now ffmpeg fails to run because it's linking to a different version of x265 dynamic library. I guess I'm dumb, but how would I get ffmpeg to recompile correctly with this patch?

```brew install -s ffmpeg``` will compile from source

**Comment by sassa4ras** [comment]
> > This is great, but now ffmpeg fails to run because it's linking to a different version of x265 dynamic library. I guess I'm dumb, but how would I get ffmpeg to recompile correctly with this patch?
> 
> `brew install -s ffmpeg` will compile from source

Great, thanks!

I'm a linux guy so I'm still getting the hang of MacOS peculiarities

**Comment by silentj** [comment]
Thanks @sassa4ras - I'm guessing that's required anytime `ffmepg` is updated in `brew`, too.  I've updated my original comment with that tip.

**Comment by jpyle490** [comment]
While trying @silentj's above, I'm seeing an error:
```Undefined symbols for architecture arm64:
  "x265_entropyStateBits", referenced from:
      _x265_costCoeffNxN_neon in pixel-util.S.o
      _x265_10bit_costCoeffNxN_neon in libx265_main10.a(pixel-util.S.o)
      _x265_12bit_costCoeffNxN_neon in libx265_main12.a(pixel-util.S.o)
     (maybe you meant: _x265_entropyStateBits)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libx265.207.dylib] Error 1
make[1]: *** [CMakeFiles/x265-shared.dir/all] Error 2
make: *** [all] Error 2```
```
Regardless of whether I specify the revision in x265.rb, or if I leave it at 'master', it still starts the compilation with:

```
% brew install --HEAD x265
==> Fetching x265
######################################################################## 100.0%
==> Cloning https://bitbucket.org/multicoreware/x265_git.git
Updating /Users/jpyle/Library/Caches/Homebrew/x265--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 7f247b623 fix x265 zonefile feature
```

It seems 'master' is pulling instead of the specific revision. I, too, am coming from Linux and still learning my way around the intricacies here. Is there something else that needs clearing before I try to re-install?

**Comment by AlexanderWillner** [comment]
As it still doesn't seem to work (at least not all configurations, e.g. see https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/pull/98#issuecomment-1871398970) I suppose this ticket should be re-opened?

**Comment by retokromer** [comment]
This seems to be an upstream issue, not an issue of the formula maintained here.
