### ISSUE TITLE
ERROR: chromaprint not found

### ISSUE THREAD

**Issue by KlausJokisuo** [homebrew-ffmpeg/homebrew-ffmpeg#89]
## Bug Reports

⚠️ **This is for bug reports with the `homebrew-ffmpeg` tap only.** Please do not file a bug report if your issue relates to any of the following:

- Homebrew itself (see the [brew](https://github.com/Homebrew/brew/) issue tracker or their [discussion forum](https://github.com/Homebrew/discussions/discussions))
- The `ffmpeg` formula officially supplied by Homebrew
- An error with ffmpeg itself (use [trac.ffmpeg.org](https://trac.ffmpeg.org/) to file a bug, or the [`ffmpeg-user` mailing list](https://ffmpeg.org/contact.html#MailingLists))

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information.**

- [X] I ran `brew update` and can still reproduce the problem
- [X] I ran `brew doctor`, fixed all issues and can still reproduce the problem
- [X] I ran `brew config` and `brew doctor` and included their output with my issue
- [X] I verified that this is an issue with *this* tap and not any other `ffmpeg` version

## Expected behavior

Install ffmpeg with chromaprint

## Actual behavior

Installation failed because of an error.

## Command

The exact command you were trying to run:

```
brew install homebrew-ffmpeg/ffmpeg/ffmpeg --with-chromaprint
```

The output that you got:

```
==> Installing ffmpeg from homebrew-ffmpeg/ffmpeg
==> Downloading https://github.com/FFmpeg/FFmpeg/archive/refs/tags/n4.4.tar.gz
Already downloaded: /Users/klaus/Library/Caches/Homebrew/downloads/3474f9c0619c2a34a7ceb034099580e561b51e988fb3aa7f1dcc6ed23b4197d4--FFmpeg-n4.4.tar.gz
==> ./configure --prefix=/opt/homebrew/Cellar/ffmpeg/4.4-with-options_1 --enable-shared --cc=clang --host-cflags= --host-ldflag
Last 15 lines from /Users/klaus/Library/Logs/Homebrew/ffmpeg/01.configure:
--enable-demuxer=dash
--disable-libjack
--disable-indev=jack
--enable-opencl
--enable-videotoolbox
--disable-htmlpages
--enable-chromaprint

ERROR: chromaprint not found

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.

Do not report this issue to Homebrew/brew or Homebrew/core!

```

## Output of `brew config` and `brew doctor` commands

`brew config`:

```
HOMEBREW_VERSION: 3.2.6-28-g0fc7762
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0fc7762e997432694cff49a7065f88ea0e3b6eba
Last commit: 9 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c83224259daa54b399573296271777d9019ca512
Core tap last commit: 10 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0.5 build 1205
Git: 2.32.0 => /opt/homebrew/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.5.1-arm64
CLT: 12.5.0.22.9
Xcode: N/A
Rosetta 2: false
```

`brew doctor`:

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are missing dependencies.
You should `brew install` the missing dependencies:
  brew install ffmpeg

Run `brew missing` for more details.
```

**Comment by slhck** [comment]
```
Warning: Some installed formulae are missing dependencies.
You should `brew install` the missing dependencies:
  brew install ffmpeg
```

This makes me curious. Please do a:

```
brew uninstall ffmpeg --force
brew install chromaprint
```

and then reinstall the formula from this tap:

```
brew install homebrew-ffmpeg/ffmpeg/ffmpeg --with-chromaprint
```

**Comment by retokromer** [comment]
Hello @KlausJokisuo, did the procedure explained under [Troubleshooting](https://github.com/homebrew-ffmpeg/homebrew-ffmpeg#troubleshooting) and repeated above by @slhck resolve your issue?

**Comment by KlausJokisuo** [comment]
Thanks! It seems like that did the trick.
