### ISSUE TITLE
opencv not working after homebrew-ffmpeg installation

### ISSUE THREAD

**Issue by jotzet79** [homebrew-ffmpeg/homebrew-ffmpeg#93]
## Bug Reports

- [x] I ran `brew update` and can still reproduce the problem
- [x] I ran `brew doctor`, fixed all issues and can still reproduce the problem
- [x] I ran `brew config` and `brew doctor` and included their output with my issue
- [x] I verified that this is an issue with *this* tap and not any other `ffmpeg` version

## Expected behavior

opencv_annotation should run without issues, when installing this tap.

## Actual behavior

I had installed previously this tap already including all options, but when I have to install opencv, I have to wipe ffmpeg first to be able to install opencv correctly.

After opencv installation including the base FFmpeg, opencv_annotation just runs fine. However after installing "homebrew-ffmpeg" it seems to be missing the libavresample dylib.

Thank you,
Joachim

## Command

```
opencv_annotation 
```

The output that you got:

```
dyld: Library not loaded: /usr/local/opt/ffmpeg/lib/libavresample.4.dylib
  Referenced from: /usr/local/Cellar/opencv/4.5.3_3/lib/libopencv_videoio.4.5.3.dylib
  Reason: image not found
Abort trap: 6
```

## Output of `brew config` and `brew doctor` commands

`brew config`:

```
HOMEBREW_VERSION: 3.3.3-36-g0730fa7
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0730fa74f654845598b8bb48dc5bccb3a07ef2f1
Last commit: 14 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7949d844e9426e3d21c2b35e9317944c043a8297
Core tap last commit: 58 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.eUmjQldbiK/org.xquartz:0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: octa-core 64-bit haswell
Clang: 12.0.0 build 1200
Git: 2.33.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.0.0.32.29
Xcode: 12.4 => /Applications/Development/Xcode.app/Contents/Developer
```

`brew doctor`:

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  ilmbase
  libelf
```

**Comment by jotzet79** [comment]
Hmmm, I just read https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/issues/68, so apparently libavresample is deprecated... :(

**Comment by slhck** [comment]
I'm surprised it's still enabled in the `Homebrew/brew` version:

https://github.com/Homebrew/homebrew-core/blob/dcfd624855c5c3af15596d40fa9480de9b506002/Formula/ffmpeg.rb#L119-L121

But I would not want to enable it here for it being deprecated, as mentioned in the other issue.

**Comment by retokromer** [comment]
Indeed, it was not removed in the new release. I guess, that it got forgotten.

**Comment by slhck** [comment]
Closing for now, see #68. For deprecated libraries, we recommend using a manual build.
