### ISSUE TITLE
Brewing custom ffmpeg but failure at metal execution

### ISSUE THREAD

**Issue by tommyknchan** [homebrew-ffmpeg/homebrew-ffmpeg#96]
I was homebrewing ffmpeg use custom configs as follow:
`brew install homebrew-ffmpeg/ffmpeg/ffmpeg --with-libcaca --with-openjpeg --with-fdk-aac --HEAD`

Under working environment of MacOS Big Sur 11.6.1 and Xcode command line tool version 13.2. Yet, it happened failure of ffmpeg installation with the log follows:
```
==> make install
Last 15 lines from /Users/tommy/Library/Logs/Homebrew/ffmpeg/02.make:
CC	libavfilter/lavfutils.o
CC	libavfilter/log2_tab.o
CC	libavfilter/lswsutils.o
OBJCC	libavfilter/metal/utils.o
HOSTCC	ffbuild/bin2c_host.o
xcrun metal libavfilter/metal/vf_yadif_videotoolbox.metal -o libavfilter/metal/vf_yadif_videotoolbox.metal.air

Failed to execute metal libavfilter/metal/vf_yadif_videotoolbox.metal -o libavfilter/metal/vf_yadif_videotoolbox.metal.air

Xcode and/or the CLT appear to be misconfigured. Try one or both of the following:
  xcodebuild -license
  sudo xcode-select --switch /path/to/Xcode.app

make: *** [libavfilter/metal/vf_yadif_videotoolbox.metal.air] Error 1
make: *** Waiting for unfinished jobs....

```

I've reopened the terminal and test the ffmpeg but with no avail, as well as I've already reset the xcode-select to CTL path. I'm sick about installing GUI version of Xcode as its large size is a great pain. Can someone advise how to fix the problem for successful installation? Thank you.

**Comment by retokromer** [comment]
Thank you @tommyknchan for reporting! Are you on a Inter or an AArch64 (ARM) maschine?

**Comment by retokromer** [comment]
@tommyknchan Please provide the full information, as indicated when you opened the bug report.

@slhck I have troubles with `libavfilter/metal/vf_yadif_videotoolbox.metal.air` when compiling the head on Intel, but it works fine on AArch64. The release works on both Mac architectures on my end. By chance, do you know if “something” has been modified recently?

**Comment by tommyknchan** [comment]
> Thank you @tommyknchan for reporting! Are you on an Intel or an AArch64 (ARM) machine?

No, I'm still using an Intel Macbook Pro (Retina 13-inch, Late 2013 edition)

**Comment by slhck** [comment]
> And how can I generate the log?

Everything we would have liked to see was contained in the bug report template that you deleted when posting this issue.

@retokromer Unfortunately (well, it's not so bad, actually) I don't have an Intel Mac anymore, so I cannot test it. I saw that the filter you are referencing has only been introduced recently.

If there is any compilation error, I suggest reporting it to https://trac.ffmpeg.org/ or sending an email to the `ffmpeg-devel` mailing list. I think there isn't much we can do here.

**Comment by retokromer** [comment]
>I think there isn't much we can do here.

That was my impression as well. Thank you for confirming, @slhck ! I’ll check in FFmpeg’s trac if that was already reported.

**Comment by slhck** [comment]
@balupton Seems you do not have `librsvg` installed? I think this is a different issue altogether and warrants a new ticket.

**Comment by countzyx** [comment]
Having the same issue. Checking pkg-config shows no issues with librsvg-2.0. This is happening on both on x64 and arm64 as of this version (5.1.2).

> Here's my log:
> 
> ```
> < 'brew' 'install' 'homebrew-ffmpeg/ffmpeg/ffmpeg' '--with-aribb24' '--with-chromaprint' '--with-fdk-aac' '--with-jack' '--with-libaribb24' '--with-libbluray' '--with-libbs2b' '--with-libcaca' '--with-libgsm' '--with-libmodplug' '--with-libopenmpt' '--with-librist' '--with-librsvg' '--with-libsoxr' '--with-libssh' '--with-libvidstab' '--with-libvmaf' '--with-libxml2' '--with-opencore-amr' '--with-openh264' '--with-openjpeg' '--with-openssl' '--with-openssl@1.1' '--with-rav1e' '--with-rtmpdump' '--with-rubberband' '--with-speex' '--< 'brew' 'install' 'homebrew-ffmpeg/ffmpeg/ffmpeg' '--with-aribb24' '--with-chromaprint' '--with-fdk-aac' '--with-jack' '--with-libaribb24' '--with-libbluray' '--with-libbs2b' '--with-libcaca' '--with-libgsm' '--with-libmodplug' '--with-libopenmpt' '--with-librist' '--with-librsvg' '--with-libsoxr' '--with-libssh' '--with-libvidstab' '--with-libvmaf' '--with-libxml2' '--with-opencore-amr' '--with-openh264' '--with-openjpeg' '--with-openssl' '--with-openssl@1.1' '--with-rav1e' '--with-rtmpdump' '--with-rubberband' '--with-speex' '--with-srt' '--with-svt-av1' '--with-tesseract' '--with-two-lame' '--with-webp' '--with-xvid' '--with-zeromq' '--with-zimg' >
> ==> Fetching dependencies for homebrew-ffmpeg/ffmpeg/ffmpeg: aribb24
> ==> Fetching aribb24
> ==> Downloading https://ghcr.io/v2/homebrew/core/aribb24/manifests/1.0.4
> ==> Downloading https://ghcr.io/v2/homebrew/core/aribb24/blobs/sha256:60ea5e1c7b35cde769b03c6172b4ff78dec340a91f8ae2e1c6b490fdce65c34a
> ==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:60ea5e1c7b35cde769b03c6172b4ff78dec340a91f8ae2e1c6b490fdce65c34a?se=2023-01-20T12%3A35%3A00Z&sig=GGfzmYmL%2FPes2IOuwWN7pw6LlL65vKMnz3FiTggGfUE%3D&sp=r&spr=https&sr=b&sv=2019-12-12
> ==> Fetching homebrew-ffmpeg/ffmpeg/ffmpeg
> ==> Downloading https://ffmpeg.org/releases/ffmpeg-5.1.2.tar.xz
> ==> Installing ffmpeg from homebrew-ffmpeg/ffmpeg
> ==> Installing dependencies for homebrew-ffmpeg/ffmpeg/ffmpeg: aribb24
> ==> Installing homebrew-ffmpeg/ffmpeg/ffmpeg dependency: aribb24
> ==> Pouring aribb24--1.0.4.arm64_ventura.bottle.tar.gz
> 🍺  /opt/homebrew/Cellar/aribb24/1.0.4: 14 files, 203.7KB
> ==> Installing homebrew-ffmpeg/ffmpeg/ffmpeg --with-chromaprint --with-fdk-aac --with-jack --with-libaribb24 --with-libmodplug --with-libopenmpt --with-librist --with-librsvg --with-libsoxr --with-libssh --with-tesseract --with-libvidstab --with-opencore-amr --with-openh264 --with-openjpeg --with-openssl --with-rav1e --with-svt-av1 --with-rtmpdump --with-rubberband --with-webp --with-zeromq --with-zimg --with-srt --with-libvmaf --with-libxml2 --with-aribb24 --with-libbluray --with-libbs2b --with-libcaca --with-libgsm --with-openssl@1.1 --with-speex --with-two-lame --with-xvid
> ==> ./configure --prefix=/opt/homebrew/Cellar/ffmpeg/5.1.2-with-options_1 --enab
> Last 15 lines from /Users/balupton/Library/Logs/Homebrew/ffmpeg/01.configure:
> --enable-openssl
> --enable-nonfree
> --enable-libjack
> --enable-indev=jack
> --enable-version3
> --enable-libopencore-amrnb
> --enable-libopencore-amrwb
> 
> ERROR: librsvg-2.0 not found using pkg-config
> 
> If you think configure made a mistake, make sure you are using the latest
> version from Git.  If the latest version fails, report the problem to the
> ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.libera.chat.
> Include the log file "ffbuild/config.log" produced by configure as this will help
> solve the problem.
> 
> Do not report this issue to Homebrew/brew or Homebrew/core!
> 
> These open issues may also help:
> Brewing custom ffmpeg but failure at metal execution https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/issues/96
> </ 'brew' 'install' 'homebrew-ffmpeg/ffmpeg/ffmpeg' '--with-aribb24' '--with-chromaprint' '--with-fdk-aac' '--with-jack' '--with-libaribb24' '--with-libbluray' '--with-libbs2b' '--with-libcaca' '--with-libgsm' '--with-libmodplug' '--with-libopenmpt' '--with-librist' '--with-librsvg' '--with-libsoxr' '--with-libssh' '--with-libvidstab' '--with-libvmaf' '--with-libxml2' '--with-opencore-amr' '--with-openh264' '--with-openjpeg' '--with-openssl' '--with-openssl@1.1' '--with-rav1e' '--with-rtmpdump' '--with-rubberband' '--with-speex' '--with-srt' '--with-svt-av1' '--with-tesseract' '--with-two-lame' '--with-webp' '--with-xvid' '--with-zeromq' '--with-zimg' >[1]
> ```

**Comment by genevera** [comment]
> Having the same issue on MacOS Ventura. Checking pkg-config shows noln issues with librsvg-2.0. This is happening on both on x64 and arm64 as of this version (5.1.2). It did not happen before now.
> 

I commented out ln 157 of /opt/homebrew/Library/Taps/homebrew-ffmpeg/homebrew-ffmpeg/Formula/ffmpeg.rb and it intalled for me.  It's a dirty hack but it seems to have worked.

**Comment by retokromer** [comment]
@genevera Do you encounter the same issue with version 6.0?

**Comment by genevera** [comment]
@retokromer I do not!  Seems to install just fine.

```bash
brew reinstall homebrew-ffmpeg/ffmpeg/ffmpeg --with-fdk-aac --with-game-music-emu --with-jack --with-libbs2b --with-libcaca --with-libgsm --with-libmodplug --with-libopenmpt --with-librist **--with-librsvg** --with-libsoxr --with-libssh --with-libvidstab --with-libvmaf --with-libxml2 --with-libzvbi --with-opencore-amr --with-openh264 --with-openjpeg --with-openssl --with-openssl@1.1 --with-rav1e --with-rtmpdump --with-rubberband --with-speex --with-srt --with-svt-av1 --with-tesseract --with-two-lame--with-webp --with-xvid --with-zeromq --with-zimg
==> Fetching homebrew-ffmpeg/ffmpeg/ffmpeg
==> Downloading https://ffmpeg.org/releases/ffmpeg-6.0.tar.xz
Already downloaded: /Users/genevera/Library/Caches/Homebrew/downloads/cde06afa988dec3565a51f2a2b503db685b5a78ba8ecc7f3c95562c750a9d838--ffmpeg-6.0.tar.xz
==> Reinstalling homebrew-ffmpeg/ffmpeg/ffmpeg --with-fdk-aac --with-game-music-emu --with-jack --with-libmodplug --with-libopenmpt --with-librist **--with-librsvg** --wit
==> ./configure --prefix=/opt/homebrew/Cellar/ffmpeg/6.0-with-options --enable-shared --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libaom --enable-libdav1d --
==> make install
==> make alltools
Warning: The default `tesseract` dependency includes limited language support.
To add all supported languages, install the `tesseract-lang` formula.
🍺  /opt/homebrew/Cellar/ffmpeg/6.0-with-options: 284 files, 50.1MB, built in 1 minute 6 seconds
% ffmpeg -version
ffmpeg version 6.0 Copyright (c) 2000-2023 the FFmpeg developers
built with Apple clang version 14.0.0 (clang-1400.0.29.202)
configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/6.0-with-options --enable-shared --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libaom --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-libsnappy --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-demuxer=dash --enable-opencl --enable-audiotoolbox --enable-videotoolbox --enable-neon --disable-htmlpages --enable-libbs2b --enable-libcaca --enable-libfdk-aac --enable-libgme --enable-libgsm --enable-libmodplug --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-libsvtav1 --enable-librist **--enable-librsvg** --enable-librtmp --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtesseract --enable-libtwolame --enable-libvidstab --enable-libvmaf --enable-libwebp --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzvbi --enable-libzmq --enable-openssl --enable-nonfree --enable-libjack --enable-indev=jack --enable-libzvbi --enable-version3 --enable-libopencore-amrnb --enable-libopencore-amrwb
libavutil      58.  2.100 / 58.  2.100
libavcodec     60.  3.100 / 60.  3.100
libavformat    60.  3.100 / 60.  3.100
libavdevice    60.  1.100 / 60.  1.100
libavfilter     9.  3.100 /  9.  3.100
libswscale      7.  1.100 /  7.  1.100
libswresample   4. 10.100 /  4. 10.100
libpostproc    57.  1.100 / 57.  1.100
```

**Comment by retokromer** [comment]
Thank you! I guess it’s now resolved. If not, feel free to reopen the issue.
